var lang_spanish={
_Live:  "Vista en directo",

_Live_fish: "Fisheye View",

_Administrator:  "Administrador",
_User:  "Usuario",
_Logout:  "Cerrar sesión",
_Language:  "Idioma",

_Snapshot:  "instantánea",

_Manual_Recording:  "Grabación manual",

_Media_Player:  "Medios jugador",

_Lang_en:  "English",

_Lang_zh_cn:  "简体中文",

_Lang_zh_tw:  "繁體中文",

_Lang_french:  "Français",

_Lang_german:  "Deutsche",

_Lang_italian:  "Italiano",

_Lang_portuguese:  "Português",

_Lang_spanish:  "Español",

_Lang_russian:  "Pусский",

_Lang_japanese:  "日本語",

_PlayStream1:  "Reproduciendo Stream1",

_PlayStream2:  "Reproduciendo Stream2",
_PlayStream3:  "Reproduciendo Stream3",
_Configuration:  "Configuración",
_Menu_Image:  "Parámetros de imagen",
_Codec:  "Códec",
_Current_Compression_Mode:  "Modo de compresión actual",
_Current_Profile:  "Perfil actual",
_Profile:  "Perfil",
_Edit_Profile:  "Editar perfil",
_Compression_Profiles:  "Perfiles de compresión",
_CBR:  "CBR",
_VBR:  "VBR",
_Resolution:  "Resolución",
_Frame_Rate:  "Tasa de fotogramas",
_GOP_Length:  "Longitud GOP",
_Rate_Control:  "Control de tasa",
_VBR_BitRate_Max:  "Tasa máxima de bits VBR",
_VBR_BitRate_Min:  "Tasa mínima de bits VBR",
_CBR_BitRate:  "Tasa de bits CBR",
_Quality:  "Calidad",
_SaveProfile:  "Guardar perfil",
_High:  "Alta",
_Mid:  "Media",
_Low:  "Baja",
_Qos:  "Punto de codificación QoS (DSCP)",
_Menu_Image_exposure:  "Exposición",
_Exposure_Mode:  "Modo de exposición",
_Auto_Exposure:  "Exposición automática",
_AES:  "AES",
_ALC:  "ALC",
_Flickerless:  "Sin parpadeos",
_Slow_Shutter:  "Obturador lento",
_Max_Gain:  "Ganancia máxima",
_Manual_Exposure:  "Exposición manual ",

_Shutter_Speed:  "Velocidad del obturador",

_Manual_Gain:  "Ganancia manual",

_Illumination_Control:  "Control de la iluminación",

_Exposure_MISC:  "Exposición avanzada",

_EV_adjustment:  "Compensación EV",

_Day_Night:  "Día y noche",

_Day_to_Night:  "Límite de Día a Noche",

_Night_to_Day:  "Límite de Noche a Día",

_Minus: "-",

_Plus: "+",

_Switch_Delay_Time:  "Cambiar la hora de demora",

_Adc_block:  "Detección del valor actual",

_Noise_Reduction:  "Reducción de ruido",

_BLC:  "BLC",

_WDR:  "WDR",
_upper_2_3rd:  "2/3 arriba",
_lower_2_3rd:  "2/3 abajo",
_center_1_3rd:  "1/3 centro",
_center_1_6th:  "1/6 centro",
_Left:  "Izquierdo",
_Right:  "Derecho",

_Full:  "Completa",

_Custom: "Personalizar",

_ir_mode:  "Modo IR",
_ir_level:  "Nivel IR",
_Menu_Image_white_balance:  "Balance de blanco",
_White_Balance_Mode:  "Modo de balance de blanco",
_R_Gain:  "Ganancia R",
_G_Gain:  "Ganancia G",
_B_Gain:  "Ganancia B",
_Menu_Image_basic_color:  "Color básico",
_Brightness:  "Brillo",
_Contrast:  "Contraste",
_Hue:  "Matiz",
_Saturation:  "Saturación",
_Sharpness:  "Nitidez",
_Gamma_Correction:  "Corrección gamma",
_Flip_Mirror:  "Orientación de vídeo",
_Flip:  "Voltear",
_Mirror:  "Simetría",
_Both:  "Ambos",
_Menu_Image_smart_encoding: "Codificación Inteligente",
_Menu_Image_privacy:  "Zona de privacidad",
_Menu_Image_roi:  "ROI",
_Privacy_Color_Setting:  "Configuración de color de privacidad",
_Black:  "Negro",
_Grey:  "Gris",
_White:  "Blanco",
_Save_Mask_Zone:  "Guardar zona de máscara",
_Clean_Mask_Zone:  "Limpiar zona de máscara",

_Save_Window:  "Guardar Ventana",

_Clean_Window:  "Limpiar Ventana",

_Menu_Image_focus:  "Control de objetivo remoto",

_Focal_Length_Control:  "Control de zoom",

_Focal_window: "Área de enfoque",

_Day_Night_Focus_Control:  "Control del enfoque de día y noche",

_Speed:  "Velocidad de zoom",

_Zoom_In:  "Ampliar",

_Zoom_Out:  "Reducir",

_Out_Slow:  "<",
_Out_High:  "<<",
_In_Slow:  ">",
_In_High:  ">>",
_Zoom:  "Zoom",
_Focus:  "Enfoque",
_Focus_Control:  "Control de enfoque ",
_Focus_Manual_Continue:  "Enfoque manual continuo",
_Focus_Near:  "Enfoque cercano",
_Focus_Far:  "Enfoque lejano",
_Focus_Manual_Jog:  "Pasos de enfoque manual",
_Focus_Coarse:  "Paso normal",
_Focus_Fine:  "Paso fino",
_One_Push:  "AF con una pulsación",
_Do_Focus:  "Iniciar enfoque",
_Calibration_Control:  "Calibrado",
_Do_Calibration:  "Iniciar calibración",
_Menu_Network:  "Configuración de red",
_Menu_Network_ip:  "Red",
_Camera_Name:  "Nombre de la cámara",
_DHCP:  "DHCP",
_IP_Address:  "Dirección IP",
_Subnet_Mask:  "Máscara de subred",
_Default_Gateway:  "Puerta de enlace predeterminada",
_Primary_DNS:  "DNS primario",
_Secondary_DNS:  "DNS secundario",
_UPNP:  "UPnP",
_Action:  "Acción",
_OSD:  "OSD ",
_Network_setting:  "Configuración de red",
_View_current_network_setting:  "Ver configuración de la red actual",
_IPv4_addr_conf:  "Configurar dirección IPv4",
_Http_port:  "Puerto HTTP",
_Https_port:  "Puerto HTTPS",
_IPv4_addr:  "Dirección IPv4",

_IPv6: "IPv6",

_IPv6_addr_conf:  "Configurar dirección IPv6",

_Accept_IPv6_router:  "Aceptar anuncios del router IPv6",

_Enable_dhcpv6:  "Activar DHCPv6",

_IPv6_default_router_addr:  "Dirección predeterminada del router IPv6",

_IPv6_addr:  "Dirección IPv6",

_IPv6_dns:  "DNS IPv6",

_subnet_prefix_length:  "Longitud del prefijo de subred",
_bonjour:  "Bonjour",
_text:  "Texto",
_hostname:  "Nombre del host",
_View:  "Ver",
_Current_network_setting:  "Ajustes de red actual",
_FTP:  "FTP",
_Max_Simultaneous_Connection:  "Conexiones máximas simultáneas",
_FTP_Function:  "Función FTP ",
_RTSP:  "RTSP",
_Authentication:  "Autenticación ",
_RTSP_Stream:  "Secuencia RTSP",
_Transfer_Type:  "Tipo de transferencia",
_URL:  "URL",
_Multicast_Address:  "Dirección de multidifusión",
_Metadata:  "Metadatos",
_Unicast:  "Unidifusión",
_Multicast:  "Multidifusión",
_Menu_Network_snmp:  "SNMP",
_SNMP_V:  "SNMP v",
_User_Name:  "Nombre de usuario",
_Read_Write_Community_String:  "Cadena de comunidad de lectura y escritura ",
_Read_Community_String:  "Leer cadena de comunidad",
_Write_Community_String:  "Escribir cadena de comunidad",
_SNMP_Trap:  "Intercepción ",
_SNMP_Trap_Host:  "Host de intercepciones",
_SNMP_Heartbeat:  "Latido ",
_SNMP_Heartbeat_Host:  "Host de latido",
_SNMP_Heartbeat_Interval:  "Intervalo de latido",
_Download_MIB:  "Descargar MIB ",
_Download_Button:  "Descargar",
_Menu_8021x:  "802,1X",
_Protocol:  "Protocolo",
_Inner_Auth:  "Aut. interna",
_Username:  "Nombre de usuario",
_Anonymous_ID:  "Identificador anónimo",
_CA_Certificate:  "Certificado CA",
_Client_Certificate:  "Certificado de cliente",

_Private_Key:  "Clave privada",
_PEM_encoded_file:  "Archivo con codificación PEM",
_Delete:  "Eliminar",
_Private_Key_Password:  "Contraseña de clave privada",
_No_Installed_Ca:  "No instalado (inseguro, el certificado de servidor no se comprobará)",
_No_Installed:  "No instalado",
_Installed:  "Instalado (correcto)",
_IP_Filter:  "Filtro IP",
_Mode:  "Modo",
_Protocol:  "Protocolo",
_Menu_System:  "Configuración del sistema",
_Menu_System_date_time:  "Fecha y hora",
_Current_Server_Time:  "Hora actual del servidor ",
_Synchronization_Mode:  "Modo de sincronización ",
_Set_Manual:  "Manual",
_Date:  "Fecha",
_Time:  "Hora",
_Synchronize_with_Computer_Clock:  "Sincronizar con PC",
_Synchronize_with_NTP_Server:  "Sincronizar con servidor NTP",
_NTP:  "NTP ",
_NTP_Server:  "Servidor NTP",
_NTP_Synchronize_Period:  "Período de sincronización",
_NTP_Time_Adjustment_Test:  "Prueba NTP",
_Save_and_Test:  "Guardar y probar",
_DST:  "DST",
_Time_Zone:  "Zona horaria",
_Daylight_Saving:  "Ahorro energético",
_Menu_System_account:  "Administración de usuarios",
_User_List:  "Lista de usuarios",
_New_List:  "Administración de cuentas",
_Access_Level:  "Nivel de acceso",
_New_User:  "Nuevo usuario",
_Delete_User:  "Eliminar un usuario",
_Confirm_Delete_User:  "¿Está seguro de que desea eliminar este usuario?",
_Delete_User_note:  "La cámara solamente permite seis cuentas; si desea crear una nueva cuenta, elimine una existente antes.",
_User_field_note:  "El nombre de usuario debe tener entre 4 y 40 caracteres alfabéticos o numéricos (a~z, 0~9, con distinción de mayúsculas y minúsculas).",
_Exist_account:  "La cuenta existía en el sistema.",
_Passwd_field_note:  "La contraseña debe tener entre 4 y 40 caracteres o el campo tiene un carácter no válido \'",
_Admin:  "Administración ",
_Password_Confirm:  "Contraseña (Volver a confirmar)",
_Guest:  "Invitado",
_Menu_System_audio:  "Audio",
_Audio_In:  "Entrada de audio",
_Level:  "Nivel",
_G711u:  "G.711 Ley µ",
_G711a:  "G.711 Ley a",
_Audio_Out:  "Salida de audio",
_alarm_in:  "Entrada de alarma",
_Menu_sys_heater:  "Eliminar burbuja",
_current_power_source:  "Fuente actual de alimentación",
_24v:  "24V CA",
_poe:  "PoE",
_heater_note:  "Aviso importante: el calentador para eliminar burbujas solo admite la fuente de alimentación de 24V CA",
_heater_warning:  "La fuente de 24V CA debe estar conectada antes de encender la burbuja",
_Menu_System_firmware:  "Firmware",
_System_Information:  "Información del sistema ",
_Firmware_Version:  "Versión de firmware",
_MAC_Address:  "Dirección MAC",
_MCU_Version:  "Versión de MCU",
_Model_Name:  "Nombre de modelo",
_Firmware_Update_and_Package_Install:  "Actualización de firmware e instalación del paquete ",
_Upload:  "Cargar",
_Video_Type:  "Tipo de vídeo ",
_Camera_Type:  "Tipo de sistema",
_NTSC:  "NTSC",
_PAL:  "PAL",
_Import_Configuration_Settings:  "Importar configuraciones del usuario",
_Export_Configuration_Settings:  "Exportar configuraciones del usuario",
_Restart_Camera:  "Reiniciar cámara ",
_Software_Factory_Default:  "Valores predeterminados de fábrica de software",
_Hardware_Factory_Default:  "Valores predeterminados de fábrica de hardware del mando a distancia",
_Import_File:  "Importar",
_Export_File:  "Exportar",
_Menu_System_systemlog:  "Registro del sistema",
_Download_Log:  "Descargar registro",
_Refresh:  "Actualizar",
_Clean:  "Limpiar",
_Menu_Event:  "Configuración de eventos",
_Menu_Event_motion_detection:  "Detección de movimiento",
_Sensitivity:  "Sensibilidad",
_Alarm:  "Alarma",
_Alarm_Input:  "Entrada de alarma",
_NO:  "NA",
_NC:  "NC",
_Alarm_Output:  "Salida de alarma",
_Alarm_output_duration:  "Duración",
_Infinite:  "Infinito",
_audio_detection:  "Detección de audio",
_audio_alaram_level:  "Nivel de la alarma de audio",
_audio_activity:  "Actividad de audio",
_Menu_Record:  "Configuración de grabación",
_Menu_Record_ftp:  "Grabación FTP",
_FTP_Record_Conditions:  "Condiciones de grabación FTP",
_Scheduled:  "Programar",
_Alarm_In:  "Entrada de alarma",
_FTP_Server:  "Servidor FTP ",
_Scheduled_Recording_Table:  "Programar grabación en FTP ",
_Scheduled_Recording_SD_Table:  "Programar grabación en SD ",
_Day:  "Día",
_Monday:  "Lunes",
_Tuesday:  "Martes",
_Wednesday:  "Miércoles",
_Thursday:  "Jueves",
_Friday:  "Viernes",
_Saturday:  "Sábado",
_Sunday:  "Domingo",
_Schedule:  "Programar",
_Recording_Cycle:  "Ciclo de grabación",
_Recording_Time:    "Tiempo de grabación",
_Record_File_Name:  "Prefijo de nombre de archivo",
_Server_Path:  "Ruta de acceso del servidor",
_Second:  "(Segundo)",
_All_Day:  "Todo el día",
_Alarm_Setting:  "Grabación de evento de alarma en FTP (instantánea)",
_Pre_Recording_Frame:  "Marco de pre-grabación",
_Pre_Recording_Cycle:  "Ciclo de pre-grabación",
_Recording_Frame:  "Grabación de fotogramas",
_File_Name:  "Nombre de archivo",
_Motion_Setting:  "Grabación de evento de movimiento en FTP (instantánea)",
_AM:  "AM",
_PM:  "PM",
_Menu_Record_smtp:  "Grabación SMTP",
_SMTP_Record_Conditions:  "Condiciones de grabación SMTP",
_Recording_Mode:  "Modo de grabación",
_SMTP_Server:  "Servidor SMTP ",
_Sender_Mail_Address:  "Dirección de correo electrónico del remitente",
_No_Auth:  "Sin_Autorización",
_SMTP_Plain:  "SMTP_Plano",
_Login:  "Iniciar sesión",
_TLS_TTLS:  "TLS_TTLS",
_Condition_Settings_Alarm:  "Mensaje por correo electrónico (evento de alarma)",
_Subject:  "Asunto",
_Message:  "Mensaje",
_Attach_Image:  "Adjuntar imagen",
_Condition_Settings_Motion:  "Mensaje por correo electrónico (evento de movimiento)",
_Email_Address_List:  "Lista de direcciones de correo electrónico ",
_SMTP_No:  "Nº",
_Address:  "Dirección",
_Menu_Record_sd:  "Grabación SD",
_SD_Record_Conditions:  "Condiciones de grabación SD",
_Network_Loss:  "Pérdida de red",
_Alarm_Recording_Time:  "Hora de grabación de alarma",
_Motion_Recording_Time:  "Hora de grabación de movimiento",
_OverWrite:  "Sobrescritura automática",
_SD_Card_Information:  "Información de tarjeta SD",
_Usage:  "Uso",
_SD_Format:  "Formato de tarjeta SD",
_Format:  "Formato",
_record_schedule:  "Programación de grabación",
_edit_month_schedule:  "Editar la programación mensual",
_edit_week_schedule:  "Editar la programación semanal",
_edit_day_schedule:  "Editar la programación diaria",
_month_group:  "Mes del grupo",
_week_group:  "Semana del grupo",
_day_group:  "Día del grupo",
_week:  "Semana",
_hour:  "Hora",
_minute:  "Minuto",
_start_time:  "Hora de inicio",
_end_time:  "Hora de finalización",
_to:  "Para",
_close:  "Cerrar",
_status:  "Estado",
_save_event:  "Guardar evento",
_forever:  "Para siempre",
_month:  "Mes",
_record_type:  "Tipo de grabación",
_sd_record_setting:  "Ajustes de grabación SD",
_SD_Card_File_Brpwser:  "Explorador de archivo de la tarjeta SD",
_View_Files:  "Ver archivos",
_Showing:  "Mostrando",
_Page:  "página",
_Save:  "Guardar",
_Reset_to_Default:  "Restablecer valores predeterminados",
_Medium:  "Medio",
_Type:  "Tipo",
_ON:  "ACTIVADO",
_OFF:  "DESACTIVADO",
_Color:  "Color",
_BW:  "B/N",
_Auto:  "Automático",
_Manual:  "Manual",
_Enable:  "Habilitar",
_Start:  "Empezar",
_Stop:  "Detener",
_Password:  "Contraseña",
_Login_ID:  "Identificador de inicio de sesión",
_Port:  "Puerto",
_Motion:  "Movimiento",
_BasicSetting:  "Configuración básica",
_Not_yet:  "Todavía no",
_Msg_PleaseConfirmPassword:  "Confirme su contraseña.",
_Msg_PleaseSpecifyFW:  "¡Especifique la ruta de acceso de firmware!",
_Msg_PleaseSpecifyIm:  "¡Especifique la ruta de acceso del archivo de importación!",
_Msg_PleaseSpecifyImName:  "Error al abrir el archivo. Asegúrese de que el formato es *.XML.",
_Format_MJPEG_Warning:  "¡No hay códec MJPEG!\nElija un modo de códec adecuado en Configuración->Parámetros de imagen->Página Códec.",
_Format_H264_Warning:  "¡No hay códec H.264!\nElija un modo de códec adecuado en Configuración->Parámetros de imagen->Página Códec.",
_SD_Card_Warning:  "¡No hay espacio para almacenar datos!",
_SD_Card_format:  "¡Esto dará formato a la tarjeta SD! ¿Está seguro de que desea continuar?",
_Firmware_upgrade_Warning:  "¿Está seguro de que desea actualizar el firmware?",
_Reboot_Warning:  "¡Esta opción reiniciará la cámara! ¿Está seguro de que desea continuar?",
_SW_Reboot_Warning:  "Se recuperarán todos los valores predeterminados de fábrica excepto los correspondientes a la sección Red y la cámara se reiniciará automáticamente. ¿Está seguro?",
_HW_Reboot_Warning:  "Se restablecerán todos los valores predeterminados de fábrica, incluso los correspondientes a la sección Red y la cámara se reiniciará automáticamente. ¿Está seguro?",
_Waiting_Warning:  "Reiniciando la cámara. Espere... ",
_Import_Warning:  "¿Está seguro de que desea importar este archivo?",
_Upload_Warning:  "Cargando archivo. Espere... ",
_Impport_Success_Warning:  "¡La importación se realizó correctamente! La cámara se está reiniciando. Espere... ",
_Impport_Fail_Warning:  "¡Error de importación! La cámara se está reiniciando. Espere... ",
_Ipfinder_Warning:  "Busque la nueva dirección IP de la cámara comprobando la dirección MAC en el buscador de direcciones IP.",
_Camera_Type_Change_Warning:  "Cambiando el tipo de cámara. Espere... ",
_Firmware_Verify_Warning:  "Comprobando el firmware. Espere... ",
_Firmware_Install_Warning:  "Instalar el firmware. Espere... ",
_Firmware_Success_Warning:  "¡El firmware se actualizó correctamente! La cámara se está reiniciando. Espere... ",
_Firmware_Fail_Warning:  "¡Error de actualización del firmware! La cámara se está reiniciando. Espere... ",
_Reset_to_default_Warning:  "¡Se restablecerán los parámetros predeterminados de esta página! ¿Está seguro?",
_Initial:  "Inicial",
_Both_emtpy:  "La resolución y el códec no pueden estar desactivados.",
_Resoluion_emtpy:  "La resolución no puede estar desactivada.",
_Codec_emtpy:  "El códec no puede estar desactivado.",
_Reloading:  "Recargando configuración...",
_Datetime_manual_note:  "La fecha y la hora tienen un formato incorrecto. Ejemplo: aaaa/dd/mm hh:mm:ss",
_Network_Camera:  "Cámara de red",
_Information:  "Información",
_Account_Management:  "Administración de cuentas",
_Event_log:  "Registro de eventos",
_Account_setting:  "Configuración de la cuenta",
_Initialize:  "Inicializar",
_Alarm_in_out:  "E/S de alarma",
_Email_Notification:  "Notificación por correo electrónico",
_Fixed:  "Ajustar",
_Real:  "1:1",
_Full_Screen:  "Pantalla completa",
_no_card:  "¡No hay tarjeta!",
_port_field_warning:  "El campo \"número de puerto\" está siendo utilizadopor otro sistema, vuelva a introducirlo más tarde.",
_msi_warning:  "Cierre esta ventana del navegador cuando haya completado la descarga del controlador Activex y lo haya instalado.",
_quicktime_install_note:  "Se requiere tener instalado Quicktime 7.5.5. o superior para visualizar este Stream.",
_quicktime_download_note:  "Vaya a su disco de recursos o vaya a",
_invalid_ipv6_addr:  "La dirección IPv6 es inválida.",
_invalid_ipv6_prefix_length:  "La longitud del prefijo de subred es inválida.",

_video:  "Vídeo",

_none:  "NINGUNO",

_privacy:  "Privacidad",

_v3_auth_note:  "La clave de autenticación debe tener entre 8 y 64 caracteres.",

_v3_privacy_note:  "La clave de privacidad debe tener entre 8 y 64 caracteres.",

_player:  "Jugador",

_interval_note:  "El valor debe ser mayor de 30.",

_Alarm_Message:  "La palabra debe contener entre 2 y 200 caracteres",

_NAT_Setting:  "Ajuste Neto",

_Rtsp_Port:  "Puerto RTSP sobre NAT",

_Menu:  "Menú",

_Stream:  "Secuencia",

_Allow:  "Permitir",

_Deny:  "Negar",

_Smart_Encoding_Region: "Codificación regional inteligente",

_Heater:"Desempañador de burbuja",

_Heater_setting:"Configuración del desempañador de burbuja",

_Heater_note:"Aviso Importante: Para evitar el peligro de quemar, desactive la función desempañador de burbuja al instalar la cámara",

_Setting:"Configuración",

_Menu_SD_playback:"SD Playback",

_Msnapshot_note:"This page lists only record files stored on local SD card.",

_Msnapshot_remain:"Percent storage remaining:",

_Delete_all:"Delete All",

_Loading_data:"Loading data...",

_Loading_note:"Please wait as the data for your selection is loaded.",

_Reloading_note:"Please wait as the settings are reloaded.",

_Reloading_data:"Reloading data...",

_Deleting:"Deleting",

_SD_delete_all_confirm:"This will delete all mp4 files on the card and may take a long time. The SD card may not be removed during this time.Continue?",

_SD_delete_file:"Delete this file?",

_Higher_Frame_Rate: "Higher Frame Rate",

_Schedule_Reboot: "Schedule Reboot",

_Reboot_time: "Start Time",

_Fisheye: "Fisheye",

_Panaroma: "Panaroma",

_Quad: "Quad",

_Fish_view1: "View1",

_Fish_view2: "View2",

_Fish_view3: "View3",

_Fish_view4: "View4",

_msi_warning_confirm:  "The activex controller is not detected, do you want to download and install?",

_Position: "Position",

_Up_left: "Up-left",

_Up_middle: "Up-middle",

_Up_right:"Up-right",

_Bottom_left:"Bottom-left",

_Bottom_middle:"Bottom-middle",

_Bottom_right:"Bottom-right",

_External: "External",

_:  "" }


