var lang_italian={ 
_Live:  "Visione dal vivo",

_Live_fish: "Fisheye View",

_Administrator:  "Amministratore",
_User:  "Utente",
_Logout:  "Logout",

_Language:  "Lingua",

_Snapshot:  "Istantanea",

_Manual_Recording:  "Registrazione manuale",

_Media_Player:  "media eventi lettore",

_Lang_en:  "English",

_Lang_zh_cn:  "简体中文",

_Lang_zh_tw:  "繁體中文",

_Lang_french:  "Français",

_Lang_german:  "Deutsche",

_Lang_italian:  "Italiano",

_Lang_portuguese:  "Português",

_Lang_spanish:  "Español",

_Lang_russian:  "Pусский",

_Lang_japanese:  "日本語",

_PlayStream1:  "Riproduzione Stream1",

_PlayStream2:  "Riproduzione Stream2",

_PlayStream3:  "Riproduzione Stream3",

_Configuration:  "Configurazione",

_Menu_Image:  "Parametri immagine",

_Codec:  "Codec",
_Current_Compression_Mode:  "Modalità di compressione corrente",
_Current_Profile:  "Profilo corrente",
_Profile:  "Profilo",
_Edit_Profile:  "Modifica profilo",
_Compression_Profiles:  "Profili di compressione",
_CBR:  "CBR",
_VBR:  "VBR",
_Resolution:  "Risoluzione",
_Frame_Rate:  "Frame rate",
_GOP_Length:  "Lunghezza GOP",
_Rate_Control:  "Controllo velocità",
_VBR_BitRate_Max:  "Velocità bit VBR massima",
_VBR_BitRate_Min:  "Velocità bit VBR minima",
_CBR_BitRate:  "Velocità bit CBR",
_Quality:  "Qualità",
_SaveProfile:  "Salva profilo",
_High:  "Alta",
_Mid:  "Medio",
_Low:  "Bassa",
_Qos:  "Punto di codice QoS (DSCP)",
_Menu_Image_exposure:  "Esposizione",
_Exposure_Mode:  "Modalità di esposizione",
_Auto_Exposure:  "Esposizione automatica",
_AES:  "AES",
_ALC:  "ALC",
_Flickerless:  "Esclusione sfarfallio",
_Slow_Shutter:  "Otturatore lento",
_Max_Gain:  "Guadagno max.",
_Manual_Exposure:  "Esposizione manuale ",
_Shutter_Speed:  "Velocità otturatore",

_Manual_Gain:  "Guadagno manuale",

_Illumination_Control:  "Controllo illuminazione",

_Exposure_MISC:  "Esposizione avanzata",

_EV_adjustment:  "Compensazione EV",

_Day_Night:  "Giorno e notte",

_Day_to_Night:  "Soglia giorno note",

_Night_to_Day:  "Soglio giorno note",

_Minus: "-",

_Plus: "+",

_Switch_Delay_Time:  "Commuta tempo di ritardo",

_Adc_block:  "Rileva valore corrente",

_Noise_Reduction:  "Riduzione del rumore",

_BLC:  "BLC",
_WDR:  "WDR",
_upper_2_3rd:  "2°/3° superiore ",
_lower_2_3rd:  "2°/3° inferiore",
_center_1_3rd:  "1°/3° centrale",
_center_1_6th:  "1°/6° centrale",
_Left:  "Sinistra",
_Right:  "Destra",
_Full:  "Intero",

_Custom: "Personalizzare",

_ir_mode:  "Modalità IR",
_ir_level:  "Livello IR",
_Menu_Image_white_balance:  "Bilanciamento del bianco ",
_White_Balance_Mode:  "Modalità Bilanciamento bianco",
_R_Gain:  "Guadagno R",
_G_Gain:  "Guadagno G",
_B_Gain:  "Guadagno B",
_Menu_Image_basic_color:  "Colore base",
_Brightness:  "Luminosità",
_Contrast:  "Contrasto",
_Hue:  "Tonalità",
_Saturation:  "Saturazione",
_Sharpness:  "Nitidezza",
_Gamma_Correction:  "Correzione gamma",
_Flip_Mirror:  "Orientamento video",
_Flip:  "Capovolgi",
_Mirror:  "Specchio",
_Both:  "Entrambi",
_Menu_Image_smart_encoding: "Codifica Intelligente",
_Menu_Image_privacy:  "Zona privacy",
_Menu_Image_roi:  "ROI",
_Privacy_Color_Setting:  "Impostazione colore privacy",
_Black:  "Nero",
_Grey:  "Grigio",
_White:  "Bianco",
_Save_Mask_Zone:  "Salva zona maschera",
_Clean_Mask_Zone:  "Cancella zona maschera",

_Save_Window:  "Salvare Finestra",

_Clean_Window:  "Pulire Finestra",

_Menu_Image_focus:  "Controllo remoto obiettivo",
_Focal_Length_Control:  "Controllo zoom",

_Focal_window: "Area di messa a fuoco",

_Day_Night_Focus_Control:  "Controllo messa a fuoco diurno e notturno",

_Speed:  "Velocità zoom",

_Zoom_In:  "Ingrandimento",

_Zoom_Out:  "Riduzione",

_Out_Slow:  "<",

_Out_High:  "<<",
_In_Slow:  ">",
_In_High:  ">>",
_Zoom:  "Zoom",
_Focus:  "Messa a fuoco",
_Focus_Control:  "Controllo messa a fuoco ",
_Focus_Manual_Continue:  "Fuoco manuale continuo",
_Focus_Near:  "Messa a fuoco ravvicinata",
_Focus_Far:  "Messa a fuoco a distanza",
_Focus_Manual_Jog:  "Fuoco manuale progressivo",
_Focus_Coarse:  "Progressione normale",
_Focus_Fine:  "Progressione fine",
_One_Push:  "AF ad un tocco",
_Do_Focus:  "Avvia messa a fuoco",
_Calibration_Control:  "Calibrazione",
_Do_Calibration:  "Avvia calibratura",
_Menu_Network:  "Impostazioni di rete",
_Menu_Network_ip:  "Rete",
_Camera_Name:  "Nome telecamera",
_DHCP:  "DHCP",
_IP_Address:  "Indirizzo IP",
_Subnet_Mask:  "Subnet mask",
_Default_Gateway:  "Gateway predefinito",
_Primary_DNS:  "DNS primario",
_Secondary_DNS:  "DNS secondario",
_UPNP:  "UPnP",
_Action:  "Azione",
_OSD:  "OSD ",
_Network_setting:  "Impostazioni di rete",
_View_current_network_setting:  "Visualizza impostazioni di rete correnti",
_IPv4_addr_conf:  "Configura indirizzo IPv4",
_Http_port:  "Porta HTTP",
_Https_port:  "Porta HTTPS",
_IPv4_addr:  "Indirizzo IPv4",

_IPv6: "IPv6",

_IPv6_addr_conf:  "Configura indirizzo IPv6",

_Accept_IPv6_router:  "Accetta annunci router IPv6",

_Enable_dhcpv6:  "Abilita DHCPv6",

_IPv6_default_router_addr:  "Indirizzo router IPv6 predefinito",

_IPv6_addr:  "Indirizzo IPv6",

_IPv6_dns:  "DNS IPv6",

_subnet_prefix_length:  "Lunghezza prefisso subnet",
_bonjour:  "Bonjour",
_text:  "Testo",
_hostname:  "Nome host",
_View:  "Visualizza",
_Current_network_setting:  "Impostazioni rete correnti",
_FTP:  "FTP",
_Max_Simultaneous_Connection:  "Numero massimo di connessioni simultanee",
_FTP_Function:  "Funzione FTP ",
_RTSP:  "RTSP",
_Authentication:  "Autenticazione ",
_RTSP_Stream:  "Streaming RTSP",
_Transfer_Type:  "Tipo trasferimento",
_URL:  "URL",
_Multicast_Address:  "Indirizzo multicast",
_Metadata:  "Metadati",
_Unicast:  "Unicast",
_Multicast:  "Multicast",
_Menu_Network_snmp:  "SNMP",
_SNMP_V:  "SNMP v",
_User_Name:  "Nome utente",
_Read_Write_Community_String:  "Leggi / Scrivi stringa community ",
_Read_Community_String:  "Leggi stringa community",
_Write_Community_String:  "Scrivi stringa community",
_SNMP_Trap:  "Trap ",
_SNMP_Trap_Host:  "Host Trap",
_SNMP_Heartbeat:  "Heartbeat ",
_SNMP_Heartbeat_Host:  "Host Heartbeat",
_SNMP_Heartbeat_Interval:  "Intervallo Heartbeat",
_Download_MIB:  "Scarica MIB ",
_Download_Button:  "Download",
_Menu_8021x:  "802.1X",
_Protocol:  "Protocollo",
_Inner_Auth:  "Autorità interna",
_Username:  "Nome utente",
_Anonymous_ID:  "ID anonimo",
_CA_Certificate:  "Certificato CA",
_Client_Certificate:  "Certificato Client",

_Private_Key:  "Chiave privata",
_PEM_encoded_file:  "File codificato PEM",
_Delete:  "Elimina",
_Private_Key_Password:  "Password chiave privata",
_No_Installed_Ca:  "Non installato (non sicuro, il certificato del server non verrà verificato)",
_No_Installed:  "Non installato",
_Installed:  "Installato (OK)",
_IP_Filter:  "Filtro IP",
_Mode:  "Modalità",
_Protocol:  "Protocollo",
_Menu_System:  "Impostazioni di sistema",
_Menu_System_date_time:  "Data e ora",
_Current_Server_Time:  "Ora server corrente ",
_Synchronization_Mode:  "Modalità di sincronizzazione ",
_Set_Manual:  "Manuale",
_Date:  "Data",
_Time:  "Ora",
_Synchronize_with_Computer_Clock:  "Sincronizza con PC",
_Synchronize_with_NTP_Server:  "Sincronizza con server NTP",
_NTP:  "NTP ",
_NTP_Server:  "Server NTP",
_NTP_Synchronize_Period:  "Intervallo sincronizzazione",
_NTP_Time_Adjustment_Test:  "Test NTP",
_Save_and_Test:  "Salva e prova",
_DST:  "DST",
_Time_Zone:  "Fuso orario",
_Daylight_Saving:  "Ora legale",
_Menu_System_account:  "Gestione utenti",
_User_List:  "Elenco utenti",
_New_List:  "Gestione account",
_Access_Level:  "Livello di accesso",
_New_User:  "Nuovo utente",
_Delete_User:  "Elimina utente",
_Confirm_Delete_User:  "Si è certi di volere eliminare questo utente?",
_Delete_User_note:  "La telecamera consente solo sei account; se si vuole creare un nuovo new account prima è necessario eliminarne uno esistente.",
_User_field_note:  "Il nome utente deve contenere 4~40 lettere o numeri (a~z, 0~9, sensibile alle maiuscole/minuscole).",
_Exist_account:  "L’account esiste già nel sistema.",
_Passwd_field_note:  "La password deve contenere da 4 a 40 caratteri, oppure il campo contiene caratteri illegali come \ ‘.",
_Admin:  "admin ",
_Password_Confirm:  "Password (Riconferma)",
_Guest:  "Ospite",
_Menu_System_audio:  "Audio",
_Audio_In:  "Ingresso audio",
_Level:  "Livello",
_G711u:  "G.711 µ-law",
_G711a:  "G.711 a-law",
_Audio_Out:  "Uscita audio",
_alarm_in:  "Ingresso allarme",
_Menu_sys_heater:  "Bubble Scacciabruma",
_current_power_source:  "Sorgente di alimentazione corrente",
_24v:  "CA24V",
_poe:  "PoE",
_heater_note:  "Avviso importante: Bubble Scacciabruma riscaldatore è supportata solo dalla fonte di alimentazione AC24V",
_heater_warning:  "AC24V deve essere collegato prima di accendere Bubble",
_Menu_System_firmware:  "Firmware",
_System_Information:  "Informazioni di sistema ",
_Firmware_Version:  "Versione firmware",
_MAC_Address:  "Indirizzo MAC",
_MCU_Version:  "Versione MCU",
_Model_Name:  "Nome modello",
_Firmware_Update_and_Package_Install:  "Aggiornamento firmware e Installazione pacchetto ",
_Upload:  "Carica",
_Video_Type:  "Tipo di video ",
_Camera_Type:  "Tipo di sistema",
_NTSC:  "NTSC",
_PAL:  "PAL",
_Import_Configuration_Settings:  "Importa configurazioni utente",
_Export_Configuration_Settings:  "Esporta configurazioni utente",
_Restart_Camera:  "Riavvia la video camera",
_Software_Factory_Default:  "Impostazioni predefinite software",
_Hardware_Factory_Default:  "Impostazioni predefinite hardware remoto",
_Import_File:  "Importa",
_Export_File:  "Esporta",
_Menu_System_systemlog:  "Registro di sistema",
_Download_Log:  "Scarica registro",
_Refresh:  "Aggiorna",
_Clean:  "Cancella",
_Menu_Event:  "Impostazioni eventi",
_Menu_Event_motion_detection:  "Rilevamento movimento",
_Sensitivity:  "Sensibilità",
_Alarm:  "Allarme",
_Alarm_Input:  "Ingresso allarme",
_NO:  "NO",
_NC:  "NC",
_Alarm_Output:  "Uscita allarme",
_Alarm_output_duration:  "Durata",
_Infinite:  "Infinito",
_audio_detection:  "Rilevamento automatico",
_audio_alaram_level:  "Livello allarme audio",
_audio_activity:  "Attività audio",
_Menu_Record:  "Impostazioni registrazione",
_Menu_Record_ftp:  "Registrazione FTP",
_FTP_Record_Conditions:  "Condizioni di registrazione FTP",
_Scheduled:  "Pianificazione",
_Alarm_In:  "Ingresso allarme",
_FTP_Server:  "Server FTP ",
_Scheduled_Recording_Table:  "Registrazione pianificata su FTP ",

_Scheduled_Recording_SD_Table:  "Registrazione pianificata su SD ",

_Day:  "Giorno",

_Monday:  "Lunedì",

_Tuesday:  "Martedì",

_Wednesday:  "Mercoledì",

_Thursday:  "Giovedì",
_Friday:  "Venerdì",
_Saturday:  "Sabato",
_Sunday:  "Domenica",
_Schedule:  "Pianificazione",
_Recording_Cycle:  "Ciclo di registrazione",
_Recording_Time:    "Tempo di registrazione",
_Record_File_Name:  "Prefisso nome file",
_Server_Path:  "Percorso server",
_Second:  "(Secondo)",
_All_Day:  "Tutto il giorno",
_Alarm_Setting:  "Registrazione evento allarme su FTP (Istantanea)",
_Pre_Recording_Frame:  "Velocità pre-registrazione",
_Pre_Recording_Cycle:  "Ciclo pre-registrazione",
_Recording_Frame:  "Fotogrammi di registrazione",
_File_Name:  "Nome file",
_Motion_Setting:  "Registrazione evento rilevamento movimento su FTP (Istantanea)",
_AM:  "AM",
_PM:  "PM",
_Menu_Record_smtp:  "Registrazione SMTP",
_SMTP_Record_Conditions:  "Condizioni di registrazione SMTP",
_Recording_Mode:  "Modalità di registrazione",
_SMTP_Server:  "Server SMTP ",
_Sender_Mail_Address:  "Indirizzo e-mail mittente",
_No_Auth:  "No_Auth",
_SMTP_Plain:  "SMTP_Plain",
_Login:  "Login",
_TLS_TTLS:  "TLS_TTLS",
_Condition_Settings_Alarm:  "Messaggio e-mail (Evento allarme)",
_Subject:  "Oggetto",
_Message:  "Messaggio",
_Attach_Image:  "Allega immagine",
_Condition_Settings_Motion:  "Messaggio e-mail (Evento rilevamento movimento)",
_Email_Address_List:  "Elenco indirizzi e-mail ",
_SMTP_No:  "N.",
_Address:  "Indirizzo",
_Menu_Record_sd:  "Registrazione SD",
_SD_Record_Conditions:  "Condizioni registrazione SD",
_Network_Loss:  "Perdita di rete",
_Alarm_Recording_Time:  "Tenpo di registrazione allarme",
_Motion_Recording_Time:  "Tempo di registrazione movimento",
_OverWrite:  "Sovrascrivi automaticamente",
_SD_Card_Information:  "Informazioni scheda SD",
_Usage:  "Utilizzo",
_SD_Format:  "Formato SD",
_Format:  "Formato",
_record_schedule:  "Pianificazione registrazione",
_edit_month_schedule:  "Modifica pianificazione mensile",
_edit_week_schedule:  "Modifica pianificazione settimanale",
_edit_day_schedule:  "Modifica pianificazione giornaliera",
_month_group:  "Mese di gruppo",
_week_group:  "Settimana di gruppo",
_day_group:  "Giorno di gruppo",
_week:  "Settimana",
_hour:  "Ora",
_minute:  "Minuto",
_start_time:  "Ora inizio",
_end_time:  "Ora fine",
_to:  "A",
_close:  "Chiudi",
_status:  "Stato",
_save_event:  "Salva evento",
_forever:  "Sempre",
_month:  "Mese",
_record_type:  "Tipo di registrazione",
_sd_record_setting:  "Impostazioni registrazione SD",
_SD_Card_File_Brpwser:  "Browser file scheda SD",
_View_Files:  "Visualizza file",
_Showing:  "Mostra",
_Page:  "pagina",
_Save:  "Salva",
_Reset_to_Default:  "Ripristina su predefiniti",
_Medium:  "Media",
_Type:  "Tipo",
_ON:  "ON",
_OFF:  "OFF",
_Color:  "Colore",
_BW:  "B/N",
_Auto:  "Automatico",
_Manual:  "Manuale",
_Enable:  "Abilita",
_Start:  "Avvio",
_Stop:  "Stop",
_Password:  "Password",
_Login_ID:  "Nome utente",
_Port:  "Porta",
_Motion:  "Movimento",
_BasicSetting:  "Impostazioni di base",
_Not_yet:  "Non ora",
_Msg_PleaseConfirmPassword:  "Confermare la password.",
_Msg_PleaseSpecifyFW:  "Specificare il percorso del firmware!",
_Msg_PleaseSpecifyIm:  "Specificare il percorso del file da importare!",
_Msg_PleaseSpecifyImName:  "Apertura file non riuscita. Assicurarsi che il formato sia *.XML.",
_Format_MJPEG_Warning:  "Nessun codec MJPEG!\nScegliere una modalità codec appropriata su Configurazione -> Parametri immagine -> pagina Codec.",
_Format_H264_Warning:  "Nessun codec H.264!\nScegliere una modalità codec appropriata su Configurazione -> Parametri immagine -> pagina Codec.",
_SD_Card_Warning:  "Spazio esaurito per archiviare i dati!",
_SD_Card_format:  "Questa operazione formatterà la scheda SD! Continuare?",
_Firmware_upgrade_Warning:  "Si è certi di volere aggiornare il firmware?",
_Reboot_Warning:  "Questa operazione riavvierà la telecamera! Continuare?",
_SW_Reboot_Warning:  "Tutte le impostazioni, fatta eccezione per la sezione Rete, saranno ripristinate sui valori predefiniti e la telecamera sarà riavviata automaticamente. Continuare?",
_HW_Reboot_Warning:  "Tutte le impostazioni, inclusa la sezione Rete, saranno ripristinate sui valori predefiniti e la telecamera sarà riavviata automaticamente. Continuare?",
_Waiting_Warning:  "Riavvio telecamera, attendere... ",
_Import_Warning:  "Si è certi di volere importare questo file?",
_Upload_Warning:  "Caricamento del file, attendere... ",
_Impport_Success_Warning:  "Importazione riuscita! Riavvio della telecamera in corso, attendere... ",
_Impport_Fail_Warning:  "Importazione non riuscita! Riavvio della telecamera in corso, attendere... ",
_Ipfinder_Warning:  "Cercare il nuovo indirizzo IP della telecamera verificando l’indirizzo MAC su IP Finder.",
_Camera_Type_Change_Warning:  "Cambio di tipo di telecamera, attendere... ",
_Firmware_Verify_Warning:  "Verifica del firmware, attendere... ",
_Firmware_Install_Warning:  "Installazione del firmware, attendere... ",
_Firmware_Success_Warning:  "Aggiornamento firmware riuscito! Riavvio della telecamera in corso, attendere... ",
_Firmware_Fail_Warning:  "Aggiornamento del firmware non riuscito! Riavvio della telecamera in corso, attendere... ",
_Reset_to_default_Warning:  "I parametri di questa pagina saranno ripristinati sui valori predefiniti! Continuare?",
_Initial:  "Iniziale",
_Both_emtpy:  "Risoluzione e codec non possono essere impostati su Off.",
_Resoluion_emtpy:  "La risoluzione non può essere impostata su Off.",
_Codec_emtpy:  "Il codec non può essere impostato su Off.",
_Reloading:  "Ricaricamento impostazioni...",
_Datetime_manual_note:  "La data e l’ora hanno il formato sbagliato. Esempio: aaaa/gg/mm hh:mm:ss",
_Network_Camera:  "Telecamera di rete",
_Information:  "Informazioni",
_Account_Management:  "Gestione account",
_Event_log:  "Registro eventi",
_Account_setting:  "Impostazione account",
_Initialize:  "Inizializza",
_Alarm_in_out:  "Allarme I/O",
_Email_Notification:  "Notifica e-mail",
_Fixed:  "Adatta",
_Real:  "1:1",
_Full_Screen:  "Schermo intero",
_no_card:  "Nessuna scheda!",
_port_field_warning:  "Il campo numero di porta è in uso da un altro sistema, inserire nuovamente.",
_msi_warning:  "Chiudere la finestra del browser una volta completato il download e installato il controller activex.",
_quicktime_install_note:  "Per lo streaming è necessario Quicktime 7.5.5 o versione superiore.",
_quicktime_download_note:  "Controllare le risorse del disco o andare su",
_invalid_ipv6_addr:  "Indirizzo IPv6 non valido.",
_invalid_ipv6_prefix_length:  "Lunghezza prefisso subnet non valida.",
_video:  "Video",
_none:  "NESSUNO",
_privacy:  "Privacy",
_v3_auth_note:  "La chiave d’autenticazione deve contenere da 8 a 64 caratteri.",
_v3_privacy_note:  "La chiave di privacy deve contenere da 8 a 64 caratteri.",
_player:  "Lettore",
_interval_note:  "Il valore deve essere superiore a 30.",
_Alarm_Message:  "La parola deve essere compresa tra 2 e 200 caratteri",

_NAT_Setting:  "Impostazione Net",

_Rtsp_Port:  "Porta RTSP di NAT",

_Menu:  "Menu",

_Stream:  "Streaming",

_Allow:  "Consentire",

_Deny:  "Negare",

_Smart_Encoding_Region: "Codifica Regionale Intelligente",

_Heater:"Sbrinamento di bolle",

_Heater_setting:"Impostazione del sbrinamento di bolle",

_Heater_note:"Avviso Importante: Per evitare il rischio di scottare, disattivare la funzione di sbrinamento di bolle quando installare la telecamera",

_Setting:"Impostazione",

_Menu_SD_playback:"SD Playback",

_Msnapshot_note:"This page lists only record files stored on local SD card.",

_Msnapshot_remain:"Percent storage remaining:",

_Delete_all:"Delete All",

_Loading_data:"Loading data...",

_Loading_note:"Please wait as the data for your selection is loaded.",

_Reloading_note:"Please wait as the settings are reloaded.",

_Reloading_data:"Reloading data...",

_Deleting:"Deleting",

_SD_delete_all_confirm:"This will delete all mp4 files on the card and may take a long time. The SD card may not be removed during this time.Continue?",

_SD_delete_file:"Delete this file?",

_Higher_Frame_Rate: "Higher Frame Rate",

_Schedule_Reboot: "Schedule Reboot",

_Reboot_time: "Start Time",

_Fisheye: "Fisheye",

_Panaroma: "Panaroma",

_Quad: "Quad",

_Fish_view1: "View1",

_Fish_view2: "View2",

_Fish_view3: "View3",

_Fish_view4: "View4",

_msi_warning_confirm:  "The activex controller is not detected, do you want to download and install?",

_Position: "Position",

_Up_left: "Up-left",

_Up_middle: "Up-middle",

_Up_right:"Up-right",

_Bottom_left:"Bottom-left",

_Bottom_middle:"Bottom-middle",

_Bottom_right:"Bottom-right",

_External: "External",

_:  ""

}