var lang_portuguese={ 
_Live:  "Vista em direto",

_Live_fish: "Fisheye View",

_Administrator:  "Administrador",
_User:  "Utilizador",
_Logout:  "Terminar sessão",
_Language:  "Idioma",

_Snapshot:  "Captura de imagem",

_Manual_Recording:  "Gravação manual",

_Media_Player:  "Media reprodutor",

_Lang_en:  "English",

_Lang_zh_cn:  "简体中文",

_Lang_zh_tw:  "繁體中文",

_Lang_french:  "Français",

_Lang_german:  "Deutsche",

_Lang_italian:  "Italiano",

_Lang_portuguese:  "Português",

_Lang_spanish:  "Español",

_Lang_russian:  "Pусский",

_Lang_japanese:  "日本語",

_PlayStream1:  "Reprodução da Transmissão1",

_PlayStream2:  "Reprodução da Transmissão2 ",

_PlayStream3:  "Reprodução da Transmissão3",

_Configuration:  "Configuração",

_Menu_Image:  "Parâmetros da imagem",
_Codec:  "Codec",
_Current_Compression_Mode:  "Modo de compressão atual",
_Current_Profile:  "Perfil atual",
_Profile:  "Perfil",
_Edit_Profile:  "Editar perfil",
_Compression_Profiles:  "Perfis de compressão",
_CBR:  "CBR",
_VBR:  "VBR",
_Resolution:  "Resolução",
_Frame_Rate:  "Velocidade de fotogramas",
_GOP_Length:  "Tamanho de GOP",
_Rate_Control:  "Controlo de velocidade",
_VBR_BitRate_Max:  "Veloc. de Bits Máx. VBR",
_VBR_BitRate_Min:  "Veloc. de Bits Min. VBR",
_CBR_BitRate:  "Velocidade de bits CBR",
_Quality:  "Qualidade",
_SaveProfile:  "Guardar perfil",
_High:  "Alta",
_Mid:  "Média",
_Low:  "Baixa",
_Qos:  "Ponto de código QoS (DSCP)",
_Menu_Image_exposure:  "Exposição",
_Exposure_Mode:  "Modo de exposição",
_Auto_Exposure:  "Exposição automática",
_AES:  "AES",
_ALC:  "ALC",
_Flickerless:  "Sem cintilação",
_Slow_Shutter:  "Obturador lento",
_Max_Gain:  "Ganho máximo",
_Manual_Exposure:  "Exposição manual ",

_Shutter_Speed:  "Velocidade do obturador",

_Manual_Gain:  "Ganho manual",

_Illumination_Control:  "Controle de Iluminação",

_Exposure_MISC:  "Exposição avançada",

_EV_adjustment:  "Compensação EV",

_Day_Night:  "Dia e Noite",

_Day_to_Night:  "Limite Dia a Noite",

_Night_to_Day:  "Limite Noite ao Dia",

_Minus: "-",

_Plus: "+",

_Switch_Delay_Time:  "Tempo de Retardamento do Comutador",

_Adc_block:  "Detecção do Valor Atual",

_Noise_Reduction:  "Redução de ruído",

_BLC:  "BLC",

_WDR:  "WDR",
_upper_2_3rd:  "2/3 superior",
_lower_2_3rd:  "2/3 inferior",
_center_1_3rd:  "1/3 central",
_center_1_6th:  "1/6 central",
_Left:  "Esquerda",
_Right:  "Direita",

_Full:  "Total",

_Custom: "Personalizar",

_ir_mode:  "Modo IR",
_ir_level:  "Nível IR",
_Menu_Image_white_balance:  "Equilíbrio de brancos",
_White_Balance_Mode:  "Modo de equilíbrio de brancos",
_R_Gain:  "Ganho R",
_G_Gain:  "Ganho G",
_B_Gain:  "Ganho B",
_Menu_Image_basic_color:  "Cor básica",
_Brightness:  "Brilho",
_Contrast:  "Contraste",
_Hue:  "Tonalidade",
_Saturation:  "Saturação",
_Sharpness:  "Nitidez",
_Gamma_Correction:  "Correção de gama",
_Flip_Mirror:  "Orientação de vídeo",
_Flip:  "Inverter",
_Mirror:  "Espelhar",
_Both:  "Ambos",
_Menu_Image_smart_encoding: "Codificação Inteligente",
_Menu_Image_privacy:  "Zona de privacidade",
_Menu_Image_roi:  "ROI",
_Privacy_Color_Setting:  "Configuração de cor de privacidade",
_Black:  "Preto",
_Grey:  "Cinzento",
_White:  "Branco",
_Save_Mask_Zone:  "Guardar zona de máscara",
_Clean_Mask_Zone:  "Limpar zona de máscara",

_Save_Window:  "Salvar Janela",

_Clean_Window:  "Apagar Janela",

_Menu_Image_focus:  "Controlo remoto de lente",

_Focal_Length_Control:  "Controlo de zoom",

_Focal_window: "Área de foco",

_Day_Night_Focus_Control:  "Controle de Focalização Dia & Noite",

_Speed:  "Velocidade de zoom",

_Zoom_In:  "Aumentar zoom",

_Zoom_Out:  "Diminuir zoom",

_Out_Slow:  "<",
_Out_High:  "<<",
_In_Slow:  ">",
_In_High:  ">>",
_Zoom:  "Zoom",
_Focus:  "Foco",
_Focus_Control:  "Controlo de focagem   ",
_Focus_Manual_Continue:  "Focagem manual contínua",
_Focus_Near:  "Focagem aproximada",
_Focus_Far:  "Focagem afastada",
_Focus_Manual_Jog:  "Passos de focagem manual",
_Focus_Coarse:  "Passo normal",
_Focus_Fine:  "Passo refinado",
_One_Push:  "AF com um toque",
_Do_Focus:  "Iniciar focagem",
_Calibration_Control:  "Calibração",
_Do_Calibration:  "Iniciar calibragem",
_Menu_Network:  "Definições de rede",
_Menu_Network_ip:  "Rede",
_Camera_Name:  "Nome da câmara",
_DHCP:  "DHCP",
_IP_Address:  "Endereço IP",
_Subnet_Mask:  "Máscara de sub-rede",
_Default_Gateway:  "Gateway predefinido",
_Primary_DNS:  "DNS principal",
_Secondary_DNS:  "DNS secundário",
_UPNP:  "UPnP",
_Action:  "Acão",
_OSD:  "OSD ",
_Network_setting:  "Definições de rede",
_View_current_network_setting:  "Ver definições de rede atuais",
_IPv4_addr_conf:  "Configurar endereço IPv4",
_Http_port:  "Porta HTTP",
_Https_port:  "Porta HTTPS",
_IPv4_addr:  "Endereço IPv4",

_IPv6: "IPv6",

_IPv6_addr_conf:  "Configurar endereço IPv6",

_Accept_IPv6_router:  "Aceitar os anúncios de roteador IPV6",

_Enable_dhcpv6:  "Activar DHCPv6",

_IPv6_default_router_addr:  "Endereço do roteador padrão IPV6",

_IPv6_addr:  "Endereço IPv6",

_IPv6_dns:  "IPv6 DNS",

_subnet_prefix_length:  "Comprimento do prefixo da sub-rede",
_bonjour:  "Bonjour",
_text:  "Texto",
_hostname:  "Nome de host",
_View:  "Ver",
_Current_network_setting:  "Configurações de Rede Atual",
_FTP:  "FTP",
_Max_Simultaneous_Connection:  "Máx. de ligações simultâneas",
_FTP_Function:  "Função FTP ",
_RTSP:  "RTSP",
_Authentication:  "Autenticação ",
_RTSP_Stream:  "Transmissão RTSP",
_Transfer_Type:  "Tipo de Transferência",
_URL:  "URL",
_Multicast_Address:  "Endereço Multicast",
_Metadata:  "Metadados",
_Unicast:  "Unicast",
_Multicast:  "Multicast",
_Menu_Network_snmp:  "SNMP",
_SNMP_V:  "SNMP v",
_User_Name:  "Nome de utilizador",
_Read_Write_Community_String:  "Ler/escrever cadeia de comunidade ",
_Read_Community_String:  "Ler cadeia de comunidade",
_Write_Community_String:  "Escrever cadeia de comunidade",
_SNMP_Trap:  "Trap ",
_SNMP_Trap_Host:  "Anfitrião Trap",
_SNMP_Heartbeat:  "Heartbeat ",
_SNMP_Heartbeat_Host:  "Anfitrião Heartbeat",
_SNMP_Heartbeat_Interval:  "Intervalo Heartbeat",
_Download_MIB:  "Transferir MIB ",
_Download_Button:  "Transferir",
_Menu_8021x:  "802.1X",
_Protocol:  "Protocolo",
_Inner_Auth:  "Aut. interna",
_Username:  "Nome do utilizador",
_Anonymous_ID:  "ID anónima",
_CA_Certificate:  "Certificado de AC",
_Client_Certificate:  "Certificado de cliente",
_Private_Key:  "Chave privada",
_PEM_encoded_file:  "Ficheiro codificado por PEM",
_Delete:  "Eliminar",
_Private_Key_Password:  "Palavra-passe da chave privada",
_No_Installed_Ca:  "Não instalado (inseguro, o certificado do servidor não será verificado)",
_No_Installed:  "Não instalado",
_Installed:  "Instalado (OK)",
_IP_Filter:  "IP de Filtro",
_Mode:  "Modo",
_Protocol:  "Protocolo",
_Menu_System:  "Definições do sistema",
_Menu_System_date_time:  "Data e Hora",
_Current_Server_Time:  "Hora atual do servidor ",
_Synchronization_Mode:  "Modo de sincronização ",
_Set_Manual:  "Manual",
_Date:  "Data",
_Time:  "Hora",
_Synchronize_with_Computer_Clock:  "Sincronizar com PC",
_Synchronize_with_NTP_Server:  "Sincronizar com servidor NTP",
_NTP:  "NTP ",
_NTP_Server:  "Servidor NTP",
_NTP_Synchronize_Period:  "Período de sincronização",
_NTP_Time_Adjustment_Test:  "Teste de NTP",
_Save_and_Test:  "Salvar & Testar",
_DST:  "DST",
_Time_Zone:  "Fuso horário",
_Daylight_Saving:  "Horário de Verão",
_Menu_System_account:  "Gestão de utilizadores",
_User_List:  "Lista de utilizadores",
_New_List:  "Gestão da conta",
_Access_Level:  "Nível de acesso",
_New_User:  "Novo utilizador",
_Delete_User:  "Eliminar utilizador",
_Confirm_Delete_User:  "Deseja realmente eliminar este utilizador?",
_Delete_User_note:  "A câmara permite apenas seis contas. Se deseja criar uma nova conta, deverá eliminar primeiro uma conta existente.",
_User_field_note:  "O nome de utilizador deve conter entre 4 e 40 letras ou números ( a-z, 0-9, sensível a maiúsculas e minúsculas).",
_Exist_account:  "A conta já existe no sistema.",
_Passwd_field_note:  "A palavra-passe deve conter entre 4 e 40 caracteres ou o campo contém caracteres ilegais \'",
_Admin:  "Administrador ",
_Password_Confirm:  "Senha (Re-confirmar)",
_Guest:  "Convidado",
_Menu_System_audio:  "Áudio",
_Audio_In:  "Entrada de áudio",
_Level:  "Nível",
_G711u:  "G.711 µ-law",
_G711a:  "G.711 a-law",
_Audio_Out:  "Saída de áudio",
_alarm_in:  "Entrada de alarme",
_Menu_sys_heater:  "Bubble Defog",
_current_power_source:  "Fonte de Alimentação Atual",
_24v:  "AC24V",
_poe:  "PoE",
_heater_note:  "Aviso importante: Bubble Defog Heater só é suportado pela fonte de alimentação AC24V",
_heater_warning:  "AC24V deve estar conectado antes de habilitar Bubble",
_Menu_System_firmware:  "Firmware",
_System_Information:  "Informações do sistema ",
_Firmware_Version:  "Versão do firmware",
_MAC_Address:  "Endereço MAC",
_MCU_Version:  "Versão MCU",
_Model_Name:  "Nome do modelo",
_Firmware_Update_and_Package_Install:  "Atualizar firmware e instalar pacote ",
_Upload:  "Enviar",
_Video_Type:  "Tipo de vídeo ",
_Camera_Type:  "Tipo de sistema",
_NTSC:  "NTSC",
_PAL:  "PAL",
_Import_Configuration_Settings:  "Importar configurações do utilizador",
_Export_Configuration_Settings:  "Exportar configurações do utilizador",
_Restart_Camera:  "Reiniciar câmara",
_Software_Factory_Default:  "Predefinições de software de fábrica",
_Hardware_Factory_Default:  "Predefinições de hardware remoto de fábrica",
_Import_File:  "Importar",
_Export_File:  "Exportar",
_Menu_System_systemlog:  "Registo do sistema",
_Download_Log:  "Transferir registo",
_Refresh:  "Atualizar",
_Clean:  "Limpar",
_Menu_Event:  "Definições de evento",
_Menu_Event_motion_detection:  "Deteção de movimento",
_Sensitivity:  "Sensibilidade",
_Alarm:  "Alarme",
_Alarm_Input:  "Entrada de alarme",
_NO:  "NO",
_NC:  "NC",
_Alarm_Output:  "Saída de alarme",
_Alarm_output_duration:  "Duração",
_Infinite:  "Infinito",
_audio_detection:  "Detecção de áudio",
_audio_alaram_level:  "Nível de alarme do áudio",
_audio_activity:  "Atividade de Áudio",
_Menu_Record:  "Definições de gravação",
_Menu_Record_ftp:  "Gravação FTP",
_FTP_Record_Conditions:  "Condições de gravação FTP",
_Scheduled:  "Agendar",
_Alarm_In:  "Entrada de alarme",
_FTP_Server:  "Servidor FTP ",
_Scheduled_Recording_Table:  "Agendar gravação para FTP ",

_Scheduled_Recording_SD_Table:  "Agendar gravação para SD ",

_Day:  "Dia",

_Monday:  "Segunda-feira",
_Tuesday:  "Terça-feira",
_Wednesday:  "Quarta-feira",
_Thursday:  "Quinta-feira",
_Friday:  "Sexta-feira",
_Saturday:  "Sábado",
_Sunday:  "Domingo",
_Schedule:  "Agendar",
_Recording_Cycle:  "Ciclo de Gravação",
_Recording_Time:    "Tempo de gravação",
_Record_File_Name:  "Prefixo do nome de ficheiro",
_Server_Path:  "Caminho do servidor",
_Second:  "(Segundo)",
_All_Day:  "Todo o dia",
_Alarm_Setting:  "Gravação de evento de alarme para FTP (Captura de imagem)",
_Pre_Recording_Frame:  "Quadro de Pré Gravação",
_Pre_Recording_Cycle:  "Ciclo de Pré Gravação",
_Recording_Frame:  "Gravação de quadro",
_File_Name:  "Nome do ficheiro",
_Motion_Setting:  "Gravação de evento de movimento para FTP (Captura de imagem)",
_AM:  "AM",
_PM:  "PM",
_Menu_Record_smtp:  "Gravação SMTP",
_SMTP_Record_Conditions:  "Condições de gravação SMTP",
_Recording_Mode:  "Modo de gravação",
_SMTP_Server:  "Servidor SMTP ",
_Sender_Mail_Address:  "Endereço de e-mail do remetente",
_No_Auth:  "No_Auth",
_SMTP_Plain:  "SMTP_Plain",
_Login:  "Iniciar sessão",
_TLS_TTLS:  "TLS_TTLS",
_Condition_Settings_Alarm:  "Mensagem de e-mail (Evento de alarme)",
_Subject:  "Assunto",
_Message:  "Mensagem",
_Attach_Image:  "Anexar imagem",
_Condition_Settings_Motion:  "Mensagem de e-mail (Evento de movimento)",
_Email_Address_List:  "Lista de endereços de e-mail ",
_SMTP_No:  "N.º",
_Address:  "Endereço",
_Menu_Record_sd:  "Gravação SD",
_SD_Record_Conditions:  "Condições de gravação SD",
_Network_Loss:  "Perda de rede",
_Alarm_Recording_Time:  "Hora de gravação por alarme",
_Motion_Recording_Time:  "Hora de gravação por movimento",
_OverWrite:  "Substituir automaticamente",
_SD_Card_Information:  "Informações do cartão SD",
_Usage:  "Utilização",
_SD_Format:  "Formatar SD",
_Format:  "Formato",
_record_schedule:  "Programa de Gravação",
_edit_month_schedule:  "Editar Programa Mensal",
_edit_week_schedule:  "Editar Programa Semanal",
_edit_day_schedule:  "Editar Programa Diário",
_month_group:  "Mês do grupo",
_week_group:  "Semana do grupo",
_day_group:  "Dia do grupo",
_week:  "Semana",
_hour:  "Hora",
_minute:  "Minuto",
_start_time:  "Hora inicial",
_end_time:  "Hora Final",
_to:  "A",
_close:  "Fechar",
_status:  "Estado",
_save_event:  "Salvar caso",
_forever:  "Para Sempre",
_month:  "Mês",
_record_type:  "Tipo de Gravação",
_sd_record_setting:  "Configurações de gravação SD",
_SD_Card_File_Brpwser:  "Navegador de arquivo de Cartão SD",
_View_Files:  "Ver arquivos",
_Showing:  "ExiiMostrando",
_Page:  "Exibição",
_Save:  "Guardar",
_Reset_to_Default:  "Repor predefinição",
_Medium:  "Médio",
_Type:  "Tipo",
_ON:  "ATIVADO",
_OFF:  "DESATIVADO",
_Color:  "Cor",
_BW:  "P/B",
_Auto:  "Auto",
_Manual:  "Manual",
_Enable:  "Ativar",
_Start:  "Iniciar",
_Stop:  "Parar",
_Password:  "Palavra-passe",
_Login_ID:  "ID do início de sessão",
_Port:  "Porta",
_Motion:  "Movimento",
_BasicSetting:  "Configuração básica",
_Not_yet:  "Ainda não",
_Msg_PleaseConfirmPassword:  "Confirme a sua palavra-passe.",
_Msg_PleaseSpecifyFW:  "Especifique o caminho do firmware!",
_Msg_PleaseSpecifyIm:  "Especifique o caminho do ficheiro a importar!",
_Msg_PleaseSpecifyImName:  "Falha ao abrir o ficheiro. Certifique-se de que o formato do ficheiro é *.XML.",
_Format_MJPEG_Warning:  "Nenhum Codec MJPEG!\nEscolha um modo de codec adequado na página Configuração->Parâmetros da imagem->Codec.",
_Format_H264_Warning:  "Nenhum Codec H.264!\nEscolha um modo de codec adequado na página Configuração->Parâmetros da imagem->Codec.",
_SD_Card_Warning:  "Sem espaço para armazenar dados!",
_SD_Card_format:  "Isto irá formatar o cartão SD! Deseja realmente continuar?",
_Firmware_upgrade_Warning:  "Deseja realmente atualizar o firmware?",
_Reboot_Warning:  "Isto irá reiniciar a câmara! Deseja realmente continuar?",
_SW_Reboot_Warning:  "Todas as definições, exceto a secção de Rede, serão repostos para os valores predefinidos de fábrica e a câmara irá reiniciar automaticamente. Tem a certeza?",
_HW_Reboot_Warning:  "Todas as definições, incluindo a secção de Rede, serão repostas para os valores predefinidos de fábrica e a câmara irá reiniciar automaticamente. Tem a certeza?",
_Waiting_Warning:  "Câmara a reiniciar, aguarde... ",
_Import_Warning:  "Deseja realmente importar este ficheiro?",
_Upload_Warning:  "A enviar ficheiro, aguarde... ",
_Impport_Success_Warning:  "Importação efetuada com êxito! A câmara está a reiniciar, aguarde... ",
_Impport_Fail_Warning:  "A importação falhou! A câmara está a reiniciar, aguarde... ",
_Ipfinder_Warning:  "Procure o novo endereço da câmara IP verificando o endereço MAC no IP Finder.",
_Camera_Type_Change_Warning:  "A mudar o tipo de câmara, aguarde... ",
_Firmware_Verify_Warning:  "A verificar o firmware, aguarde... ",
_Firmware_Install_Warning:  "A instalar o firmware, aguarde... ",
_Firmware_Success_Warning:  "Firmware atualizado com êxito! A câmara está a reiniciar, aguarde... ",
_Firmware_Fail_Warning:  "A atualização do firmware falhou! A câmara está a reiniciar, aguarde... ",
_Reset_to_default_Warning:  "Os parâmetros nesta página serão repostos para os valores predefinidos! Tem a certeza?",
_Initial:  "Inicial",
_Both_emtpy:  "A resolução e o codec não podem estar desativados.",
_Resoluion_emtpy:  "A resolução não pode estar desativada.",
_Codec_emtpy:  "O codec não pode estar desativado.",
_Reloading:  "A recarregar as definições...",
_Datetime_manual_note:  "A data e a hora têm um formato incorreto. Exemplo: aaaa/dd/mm hh:mm:ss",
_Network_Camera:  "Câmara de rede",
_Information:  "Informações",
_Account_Management:  "Gestão da conta",
_Event_log:  "Registo de eventos",
_Account_setting:  "Configuração da conta ",
_Initialize:  "Iniciar",
_Alarm_in_out:  "E/S de alarme",
_Email_Notification:  "Notificação por e-mail",
_Fixed:  "Ajustar",
_Real:  "1:1",
_Full_Screen:  "Ecrã inteiro",
_no_card:  "Sem cartão!",
_port_field_warning:  "O número da porta de campo já está sendo usado para outro sistema, por favor digite novamente.",
_msi_warning:  "Feche esta janela do navegador quando você concluir o baixamento do controle activex e depois de instalá-lo.",
_quicktime_install_note:  "Quicktime 7.5.5 ou superior é requerido para esta transferência.",
_quicktime_download_note:  "Por favor consulte o seu disco de recursos ou vá ao",
_invalid_ipv6_addr:  "O endereço IPv6 é inválido.",
_invalid_ipv6_prefix_length:  "O comprimento do prefixo da sub-rede é inválido.",
_video:  "Vídeo",
_none:  "NENHUM",
_privacy:  "Privacidade",
_v3_auth_note:  "A chave de autenticação deverá conter entre 8 e 64 caracteres.",
_v3_privacy_note:  "A chave de privacidade deverá conter entre 8 e 64 caracteres.",
_player:  "Reprodutor",
_interval_note:  "O valor deve ser superior a 30.",

_Alarm_Message:  "Palavra deve estar entre 2 e 200 caracteres",

_NAT_Setting:  "Configuração Net",

_Rtsp_Port:  "RTSP Porto sobre NAT",

_Stream:  "Transmissão",

_Menu:  "Menu",

_Allow:  "Permitir",

_Deny:  "Negar",

_Smart_Encoding_Region: "Codificação regional inteligente",

_Heater:"Desembaçador de bolha",

_Heater_setting:"Configuração do desembaçador de bolha",

_Heater_note:"Aviso importante: a fim de evitar o risco de provocar queimaduras, por favor desligue a função do desembaçador de bolha ao instalar a câmera",

_Setting:"Configuração",

_Menu_SD_playback:"SD Playback",

_Msnapshot_note:"This page lists only record files stored on local SD card.",

_Msnapshot_remain:"Percent storage remaining:",

_Delete_all:"Delete All",

_Loading_data:"Loading data...",

_Loading_note:"Please wait as the data for your selection is loaded.",

_Reloading_note:"Please wait as the settings are reloaded.",

_Reloading_data:"Reloading data...",

_Deleting:"Deleting",

_SD_delete_all_confirm:"This will delete all mp4 files on the card and may take a long time. The SD card may not be removed during this time.Continue?",

_SD_delete_file:"Delete this file?",

_Higher_Frame_Rate: "Higher Frame Rate",

_Schedule_Reboot: "Schedule Reboot",

_Reboot_time: "Start Time",

_Fisheye: "Fisheye",

_Panaroma: "Panaroma",

_Quad: "Quad",

_Fish_view1: "View1",

_Fish_view2: "View2",

_Fish_view3: "View3",

_Fish_view4: "View4",

_msi_warning_confirm:  "The activex controller is not detected, do you want to download and install?",

_Position: "Position",

_Up_left: "Up-left",

_Up_middle: "Up-middle",

_Up_right:"Up-right",

_Bottom_left:"Bottom-left",

_Bottom_middle:"Bottom-middle",

_Bottom_right:"Bottom-right",

_External: "External",

_:  ""

}