var lang_german={ 
_Live:  "Echtzeitansicht",

_Live_fish: "Fisheye View",

_Administrator:  "Administrator",
_User:  "Benutzer",
_Logout:  "Abmelden",
_Language:  "Sprache",

_Snapshot:  "Momentaufnahme",

_Manual_Recording:  "Manuelle Aufnahme",

_Media_Player:  "Medien spieler",

_Lang_en:  "English",

_Lang_zh_cn:  "简体中文",

_Lang_zh_tw:  "繁體中文",

_Lang_french:  "Français",

_Lang_german:  "Deutsche",

_Lang_italian:  "Italiano",

_Lang_portuguese:  "Português",

_Lang_spanish:  "Español",

_Lang_russian:  "Pусский",

_Lang_japanese:  "日本語",

_PlayStream1:  "Stream1 Wiedergabe",

_PlayStream2:  "Stream2 Wiedergabe",

_PlayStream3:  "Stream3 Wiedergabe",

_Configuration:  "Konfiguration",

_Menu_Image:  "Bildparameter",

_Codec:  "Codec",

_Current_Compression_Mode:  "Aktueller Komprimierungsmodus",

_Current_Profile:  "Aktuelles Profil",

_Profile:  "Profil",
_Edit_Profile:  "Profil bearbeiten",
_Compression_Profiles:  "Komprimierungsprofile",
_CBR:  "CBR",
_VBR:  "VBR",
_Resolution:  "Auflösung",
_Frame_Rate:  "Bildrate",
_GOP_Length:  "GOP-Länge",
_Rate_Control:  "Frequenzsteuerung",
_VBR_BitRate_Max:  "VBR-Bitrate Max.",
_VBR_BitRate_Min:  "VBR-Bitrate Min.",
_CBR_BitRate:  "CBR-Bitrate",
_Quality:  "Qualität",
_SaveProfile:  "Profil speichern",
_High:  "Hoch",
_Mid:  "Mittel",
_Low:  "Gering",
_Qos:  "QoS (DSCP) Codepoint",
_Menu_Image_exposure:  "Belichtung",
_Exposure_Mode:  "Belichtungsmodus",
_Auto_Exposure:  "Auto-Belichtung",
_AES:  "AES",
_ALC:  "ALC",
_Flickerless:  "Flimmerfrei",
_Slow_Shutter:  "Langsamer Verschluss",
_Max_Gain:  "Max. Verstärkung",
_Manual_Exposure:  "Manuelle Belichtung ",
_Shutter_Speed:  "Verschlussgeschwindigkeit",

_Manual_Gain:  "Manuelle Verstärkung",

_Illumination_Control:  "Belichtungssteuerung",

_Exposure_MISC:  "Erweiterte Belichtung",

_EV_adjustment:  "BK-Kompensation",

_Day_Night:  "Tag & Nacht",

_Day_to_Night:  "Tag Nacht Schwelle",

_Night_to_Day:  "Nacht Tag Schwelle",

_Minus: "-",

_Plus: "+",

_Switch_Delay_Time:  "Verzögerungszeit wechseln",

_Adc_block:  "Aktuell erkannter Wert",

_Noise_Reduction:  "Rauschunterdrückung",

_BLC:  "BLC",

_WDR:  "WDR",

_upper_2_3rd:  "Oberes 2/3",
_lower_2_3rd:  "Unteres 2/3",
_center_1_3rd:  "Mittleres 1/3",
_center_1_6th:  "Mittleres 1/6",
_Left:  "Links",
_Right:  "Rechts",
_Full:  "Voll",

_Custom: "Benutzerdefiniert",

_ir_mode:  "IR-Modus",
_ir_level:  "IR-Niveau",
_Menu_Image_white_balance:  "Weißabgleich",
_White_Balance_Mode:  "Weißabgleich-Modus",
_R_Gain:  "R-Verstärkung",
_G_Gain:  "G-Verstärkung",
_B_Gain:  "B-Verstärkung",
_Menu_Image_basic_color:  "Basisfarbe",
_Brightness:  "Helligkeit",
_Contrast:  "Kontrast",
_Hue:  "Farbton",
_Saturation:  "Sättigung",
_Sharpness:  "Schärfe",
_Gamma_Correction:  "Gamma-Korrektur",
_Flip_Mirror:  "Videoausrichtung",
_Flip:  "Umkehren",
_Mirror:  "Spiegeln",
_Both:  "Beides",
_Menu_Image_smart_encoding: "Intelligente Kodierung",
_Menu_Image_privacy:  "Privatsphärebereich",
_Menu_Image_roi:  "ROI",
_Privacy_Color_Setting:  "Privatsphäre-Farbeinstellung",
_Black:  "Schwarz",
_Grey:  "Grau",
_White:  "Weiß",
_Save_Mask_Zone:  "Maskenzone speichern",
_Clean_Mask_Zone:  "Maskenzone bereinigen",

_Save_Window:  "Fenster speichern",

_Clean_Window:  "Fenster löschen",

_Menu_Image_focus:  "Externe Objektivsteuerung",

_Focal_Length_Control:  "Zoomsteuerung",

_Focal_window: "Fokusbereich",

_Day_Night_Focus_Control:  "Tag & Nacht Fokussteuerung",

_Speed:  "Zoomgeschwindigkeit",

_Zoom_In:  "Vergrößern",

_Zoom_Out:  "Verkleinern",
_Out_Slow:  "<",
_Out_High:  "<<",
_In_Slow:  ">",
_In_High:  ">>",
_Zoom:  "Zoom",
_Focus:  "Fokus",
_Focus_Control:  "Fokussteuerung ",
_Focus_Manual_Continue:  "Manueller kontinuierlicher Fokus",
_Focus_Near:  "Fokus nah",
_Focus_Far:  "Fokus fern",
_Focus_Manual_Jog:  "Manueller schrittweiser Fokus",
_Focus_Coarse:  "Normaler Schritt",
_Focus_Fine:  "Feiner Schritt",
_One_Push:  "AF mit einem Tastendruck",
_Do_Focus:  "Fokus starten",
_Calibration_Control:  "Kalibrierung",
_Do_Calibration:  "Kalibrierung starten",
_Menu_Network:  "Netzwerkeinstellungen",
_Menu_Network_ip:  "Netzwerk",
_Camera_Name:  "Kameraname",
_DHCP:  "DHCP",
_IP_Address:  "IP-Adresse",
_Subnet_Mask:  "Subnetzmaske",
_Default_Gateway:  "Standard-Gateway",
_Primary_DNS:  "Primärer DNS",
_Secondary_DNS:  "Sekundärer DNS",
_UPNP:  "UPnP",
_Action:  "Aktion",
_OSD:  "OSD ",
_Network_setting:  "Netzwerkeinstellungen",
_View_current_network_setting:  "Aktuelle Netzwerkeinstellungen ansehen",
_IPv4_addr_conf:  "IPv4-Adresse konfigurieren",
_Http_port:  "HTTP-Port",
_Https_port:  "HTTPS-Port",
_IPv4_addr:  "IPv4-Adresse",

_IPv6: "IPv6",

_IPv6_addr_conf:  "IPv6-Adresse konfigurieren",

_Accept_IPv6_router:  "IPv6 Router Anfragen akzeptieren",

_Enable_dhcpv6:  "DHCPv6 aktivieren",

_IPv6_default_router_addr:  "IPv6-Standard-Router-Adresse",

_IPv6_addr:  "IPv6-Adresse",

_IPv6_dns:  "IPv6-DNS",

_subnet_prefix_length:  "Subnetzpräfixlänge",
_bonjour:  "Bonjour",
_text:  "Text",
_hostname:  "Hostname",
_View:  "Ansicht",
_Current_network_setting:  "Aktuelle Netzwerkeinstellungen",
_FTP:  "FTP",
_Max_Simultaneous_Connection:  "Max. gleichzeitige Verbindungen",
_FTP_Function:  "FTP-Funktion ",
_RTSP:  "RTSP",
_Authentication:  "Authentifizierung ",
_RTSP_Stream:  "RTSP-Stream",
_Transfer_Type:  "Transfer-Typ",
_URL:  "URL",
_Multicast_Address:  "Multicast-Adresse",
_Metadata:  "Metadaten",
_Unicast:  "Unicast",
_Multicast:  "Multicast",
_Menu_Network_snmp:  "SNMP",
_SNMP_V:  "SNMP v",
_User_Name:  "Benutzername",
_Read_Write_Community_String:  "Community-String lesen / schreiben ",
_Read_Community_String:  "Community-String lesen",
_Write_Community_String:  "Community-String schreiben",
_SNMP_Trap:  "Trap ",
_SNMP_Trap_Host:  "Trap-Host",
_SNMP_Heartbeat:  "Herzschlag ",
_SNMP_Heartbeat_Host:  "Herzschlag-Host",
_SNMP_Heartbeat_Interval:  "Herzschlagintervall",
_Download_MIB:  "MIB herunterladen ",
_Download_Button:  "Download",
_Menu_8021x:  "802.1X",
_Protocol:  "Protokoll",
_Inner_Auth:  "Interne Auth.",
_Username:  "Benutzername",
_Anonymous_ID:  "Anonyme ID",
_CA_Certificate:  "Zertifizierungsstellenzertifikat",
_Client_Certificate:  "Client Zertifikat",

_Private_Key:  "Privater Schlüssel",
_PEM_encoded_file:  "PEM-codierte Datei",
_Delete:  "Löschen",
_Private_Key_Password:  "Kennwort für privaten Schlüssel",
_No_Installed_Ca:  "Nicht installiert (unsicher, Server-Zertifikat wird nicht geprüft)",
_No_Installed:  "Nicht installiert",
_Installed:  "Installiert (OK)",
_IP_Filter:  "IP-Filter",
_Mode:  "Modus",
_Protocol:  "Protokoll",
_Menu_System:  "Systemeinstellungen",
_Menu_System_date_time:  "Datum & Uhrzeit",
_Current_Server_Time:  "Aktuelle Serverzeit ",
_Synchronization_Mode:  "Synchronisierungsmodus ",
_Set_Manual:  "Manuell",
_Date:  "Datum",
_Time:  "Uhrzeit",
_Synchronize_with_Computer_Clock:  "Mit PC synchronisieren",
_Synchronize_with_NTP_Server:  "Mit NTP-Server synchronisieren",
_NTP:  "NTP ",
_NTP_Server:  "NTP-Server",
_NTP_Synchronize_Period:  "Synchronisierungsdauer",
_NTP_Time_Adjustment_Test:  "NTP-Test",
_Save_and_Test:  "Speichern & Test",
_DST:  "DST",
_Time_Zone:  "Zeitzone",
_Daylight_Saving:  "Sommerzeit",
_Menu_System_account:  "Benutzerverwaltung",
_User_List:  "Benutzerliste",
_New_List:  "Kontenverwaltung",
_Access_Level:  "Zugriffsebene",
_New_User:  "Neuer Benutzer",
_Delete_User:  "Benutzer löschen",
_Confirm_Delete_User:  "Sind Sie sicher, dass Sie diesen Benutzer löschen möchten?",
_Delete_User_note:  "Die Kamera erlaubt nur sechs Konten; falls Sie ein neues Konto erstellen möchten, löschen Sie bitte zunächst ein bestehendes Konto.",
_User_field_note:  "Benutzername muss aus 4 bis 40 Buchstaben oder Ziffern bestehen (a bis z, 0 bis 9, zwischen Groß-/Kleinschreibung wird unterschieden).",
_Exist_account:  "Das Konto existiert bereits im System.",
_Passwd_field_note:  "Das Kennwort muss aus 4 bis 40 Zeichen bestehen oder das Feld enthält ungültige Zeichen \'",
_Admin:  "Admin ",
_Password_Confirm:  "Passwort (Neubestätigung)",
_Guest:  "Gast",
_Menu_System_audio:  "Audio",
_Audio_In:  "Audioeingang",
_Level:  "Stufe",
_G711u:  "G.711 µ-law",
_G711a:  "G.711 a-law",
_Audio_Out:  "Audioausgang",
_alarm_in:  "Alarmeingang",
_Menu_sys_heater:  "Blase Entnebeln",
_current_power_source:  "Aktuelle Stromquelle",
_24v:  "AC24V",
_poe:  "PoE",
_heater_note:  "Wichtiger Hinweis: Blase Entnebeln Heizung wird nur von 24 V AC Stromquelle unterstützt",
_heater_warning:  "AC24V muss angeschlossen sein, bevor Bubble eingeschaltet wird",
_Menu_System_firmware:  "Firmware",
_System_Information:  "Systeminformationen ",
_Firmware_Version:  "Firmware-Version",
_MAC_Address:  "MAC-Adresse",
_MCU_Version:  "MCU-Version",
_Model_Name:  "Modellname",
_Firmware_Update_and_Package_Install:  "Firmware aktualisieren & Paket installieren ",
_Upload:  "Hochladen",
_Video_Type:  "Videotyp ",
_Camera_Type:  "Systemtyp",
_NTSC:  "NTSC",
_PAL:  "PAL",
_Import_Configuration_Settings:  "Benutzerkonfigurationen importieren",
_Export_Configuration_Settings:  "Benutzerkonfigurationen exportieren",
_Restart_Camera:  "Kamera neu starten",
_Software_Factory_Default:  "Softwarewerksstandard",
_Hardware_Factory_Default:  "Externer Hardwarewerksstandard",
_Import_File:  "Importieren",
_Export_File:  "Exportieren",
_Menu_System_systemlog:  "Systemprotokoll",
_Download_Log:  "Download-Protokoll",
_Refresh:  "Aktualisieren",
_Clean:  "Reinigen",
_Menu_Event:  "Ereigniseinstellungen",
_Menu_Event_motion_detection:  "Bewegungserkennung",
_Sensitivity:  "Empfindlichkeit",
_Alarm:  "Alarm",
_Alarm_Input:  "Alarmeingang",
_NO:  "NO",
_NC:  "NG",
_Alarm_Output:  "Alarmausgang",
_Alarm_output_duration:  "Dauer",
_Infinite:  "Unendlich",
_audio_detection:  "Audio Erkennung",
_audio_alaram_level:  "Audio Alarmstufe",
_audio_activity:  "Audio Aktivität",
_Menu_Record:  "Aufnahmeeinstellungen",
_Menu_Record_ftp:  "FTP-Aufnahme",
_FTP_Record_Conditions:  "FTP-Aufnahmebedingungen",
_Scheduled:  "Zeitplan",
_Alarm_In:  "Alarmeingang",
_FTP_Server:  "FTP-Server ",
_Scheduled_Recording_Table:  "Zeitplanaufnahme auf FTP ",
_Scheduled_Recording_SD_Table:  "Zeitplanaufnahme auf SD ",
_Day:  "Tag",
_Monday:  "Montag",
_Tuesday:  "Dienstag",
_Wednesday:  "Mittwoch",
_Thursday:  "Donnerstag",
_Friday:  "Freitag",
_Saturday:  "Samstag",
_Sunday:  "Sonntag",
_Schedule:  "Zeitplan",
_Recording_Cycle:  "Aufzeichnungszyklus",
_Recording_Time:    "Aufnahmezeit",
_Record_File_Name:  "Dateinamenpräfix",
_Server_Path:  "Server-Pfad",
_Second:  "(Zweite)",
_All_Day:  "Ganztägig",
_Alarm_Setting:  "Alarmereignisaufnahme auf FTP (Momentaufnahme)",
_Pre_Recording_Frame:  "Vor-Aufnahme Frame",
_Pre_Recording_Cycle:  "Vor-Aufnahme Zyklus",
_Recording_Frame:  "Aufnahmebereich",
_File_Name:  "Dateiname",
_Motion_Setting:  "Bewegungsereignisaufnahme auf FTP (Momentaufnahme)",
_AM:  "AM",
_PM:  "PM",
_Menu_Record_smtp:  "SMTP-Aufnahme",
_SMTP_Record_Conditions:  "SMTP-Aufnahmebedingungen",
_Recording_Mode:  "Aufnahmemodus",
_SMTP_Server:  "SMTP-Server ",
_Sender_Mail_Address:  "eMail-Adresse Absender",
_No_Auth:  "Keine_Auth",
_SMTP_Plain:  "SMTP_Plain",
_Login:  "Anmelden",
_TLS_TTLS:  "TLS_TTLS",
_Condition_Settings_Alarm:  "eMail-Nachricht (Alarmereignis)",
_Subject:  "Betreff",
_Message:  "Mitteilung",
_Attach_Image:  "Bild anhängen",
_Condition_Settings_Motion:  "eMail-Nachricht (Bewegungsereignis)",
_Email_Address_List:  "eMail-Adressliste ",
_SMTP_No:  "Nr.",
_Address:  "Adresse",
_Menu_Record_sd:  "SD-Aufnahme",
_SD_Record_Conditions:  "SD-Aufnahmebedingungen",
_Network_Loss:  "Netzwerk getrennt",
_Alarm_Recording_Time:  "Alarmaufnahmezeit",
_Motion_Recording_Time:  "Bewegungsaufnahmezeit",
_OverWrite:  "Auto-Überschreiben",
_SD_Card_Information:  "SD-Karteninformationen",
_Usage:  "Nutzung",
_SD_Format:  "SD-Formatierung",
_Format:  "Format",
_record_schedule:  "Aufnahme Zeitplan",
_edit_month_schedule:  "Monatsplan bearbeiten",
_edit_week_schedule:  "Wochenplan bearbeiten",
_edit_day_schedule:  "Tagesplan bearbeiten",
_month_group:  "Monat der Gruppe",
_week_group:  "Woche der Gruppe",
_day_group:  "Tag der Gruppe",
_week:  "Woche",
_hour:  "Stunde",
_minute:  "Minute",
_start_time:  "Startzeit",
_end_time:  "Endzeit",
_to:  "Bis",
_close:  "Beenden",
_status:  "Status",
_save_event:  "Ereignis speichern",
_forever:  "Für immer",
_month:  "Monat",
_record_type:  "Aufnahmetyp",
_sd_record_setting:  "SD Aufnahme-Einstellungen",
_SD_Card_File_Brpwser:  "SD-Karte Datei-Browser",
_View_Files:  "Dateien anzeigen",
_Showing:  "Zeigen",
_Page:  "Seite",
_Save:  "Speichern",
_Reset_to_Default:  "Auf Standard rücksetzen",
_Medium:  "Mittel",
_Type:  "Typ",
_ON:  "EIN",
_OFF:  "AUS",
_Color:  "Farbe",
_BW:  "S/W",
_Auto:  "Auto",
_Manual:  "Manuell",
_Enable:  "Aktivieren",
_Start:  "Start",
_Stop:  "Stopp",
_Password:  "Kennwort",
_Login_ID:  "Anmeldekennung",
_Port:  "Port",
_Motion:  "Bewegung",
_BasicSetting:  "Grundeinstellung",
_Not_yet:  "Noch nicht",
_Msg_PleaseConfirmPassword:  "Bitte bestätigen Sie Ihr Kennwort.",
_Msg_PleaseSpecifyFW:  "Bitte geben Sie den Pfad der Firmware an!",
_Msg_PleaseSpecifyIm:  "Bitte geben Sie den Pfad der Importdatei an!",
_Msg_PleaseSpecifyImName:  "Öffnen der Datei fehlgeschlagen. Bitte stellen Sie sicher, dass es sich beim Dateiformat um *.XML handelt.",
_Format_MJPEG_Warning:  "Kein MJPEG-Codec!\nBitte wählen Sie einen geeigneten Codec-Modus auf der Seite Konfiguration -> Bildparameter -> Codec.",
_Format_H264_Warning:  "Kein H.264-Codec!\nBitte wählen Sie einen geeigneten Codec-Modus auf der Seite Konfiguration -> Bildparameter -> Codec.",
_SD_Card_Warning:  "Kein Platz zum Speichern der Daten!",
_SD_Card_format:  "Dadurch wird die SD-Karte formatiert! Wirklich fortfahren?",
_Firmware_upgrade_Warning:  "Firmware wirklich aktualisieren?",
_Reboot_Warning:  "Dadurch startet die Kamera neu! Wirklich fortfahren?",
_SW_Reboot_Warning:  "Alle Einstellungen mit Ausnahme des Netzwerkabschnitts werden auf den Werksstandard zurückgesetzt und die Kamera wird automatisch neu gestartet. Sind Sie sicher?",
_HW_Reboot_Warning:  "Alle Einstellungen einschließlich des Netzwerkabschnitts werden auf den Werksstandard zurückgesetzt und die Kamera wird automatisch neu gestartet. Sind Sie sicher?",
_Waiting_Warning:  "Kamera wird neu gestartet, bitte warten... ",
_Import_Warning:  "Diese Datei wirklich importieren?",
_Upload_Warning:  "Datei wird hochgeladen, bitte warten ... ",
_Impport_Success_Warning:  "Importvorgang erfolgreich! Kamera wird jetzt neu gestartet, bitte warten... ",
_Impport_Fail_Warning:  "Importvorgang fehlgeschlagen! Kamera wird jetzt neu gestartet, bitte warten... ",
_Ipfinder_Warning:  "Bitte neue Kamera-IP-Adresse durch Überprüfen der MAC-Adresse im IP Finder suchen.",
_Camera_Type_Change_Warning:  "Kameratyp wird geändert, bitte warten... ",
_Firmware_Verify_Warning:  "Firmware wird überprüft, bitte warten... ",
_Firmware_Install_Warning:  "Firmware wird installiert, bitte warten... ",
_Firmware_Success_Warning:  "Firmware-Aktualisierung erfolgreich! Kamera wird jetzt neu gestartet, bitte warten... ",
_Firmware_Fail_Warning:  "Firmware-Aktualisierung fehlgeschlagen! Kamera wird jetzt neu gestartet, bitte warten... ",
_Reset_to_default_Warning:  "Parameter auf dieser Seite werden auf den Standard rückgesetzt! Sind Sie sicher?",
_Initial:  "Initial.",
_Both_emtpy:  "Auflösung und Codec können nicht aus sein.",
_Resoluion_emtpy:  "Auflösung kann nicht aus sein.",
_Codec_emtpy:  "Codec kann nicht aus sein.",
_Reloading:  "Einstellungen werden neu geladen ...",
_Datetime_manual_note:  "Datum und Uhrzeit haben ein falsches Format. Beispiel: jjjj/tt/mm hh:mm:ss",
_Network_Camera:  "Netzwerkkamera",
_Information:  "Informationen",
_Account_Management:  "Kontenverwaltung",
_Event_log:  "Ereignisprotokoll",
_Account_setting:  "Konteneinstellung",
_Initialize:  "Initialisieren",
_Alarm_in_out:  "Alarm-I/O",
_Email_Notification:  "eMail-Benachrichtigung",
_Fixed:  "Anpassen",
_Real:  "1:1",
_Full_Screen:  "Vollbild",
_no_card:  "Keine Karte!",
_port_field_warning:  "Die Portnummer wird von einem anderen System verwendet, bitte erneut eingeben.",
_msi_warning:  "Dieses Browserfenster nach dem Download und der Installation des Active-X Controller bitte schließen.",
_quicktime_install_note:  "Quicktime 7.5.5 oder höher ist für diesen Stream notwendig.",
_quicktime_download_note:  "Bitte überprüfen Sie Ihr Laufwerk oder gehen Sie zu",
_invalid_ipv6_addr:  "Die IPv6-Adresse ist ungültig.",
_invalid_ipv6_prefix_length:  "Die Subnetz Präfixlänge ist ungültig.",
_video:  "Video",
_none:  "Ohne",
_privacy:  "Privatsphäre",
_v3_auth_note:  "Authentifizierungsschlüssel muss zwischen 8 und 64 Zeichen lang sein.",
_v3_privacy_note:  "Privatsphärenschlüssel muss zwischen 8 und 64 Zeichen lang sein.",
_player:  "Spieler",
_interval_note:  "Der Wert muss über 30 liegen.",
_Alarm_Message:  "Wort muss zwischen 2 und 200 Zeichen lang sein",

_NAT_Setting:  "Netto Einstellung",

_Rtsp_Port:  "RTSP-Port über NAT",

_Stream:  "Stream",

_Menu:  "Menü",

_Smart_Encoding_Region: "Intelligente Kodierung Region",

_Allow:  "Erlauben",

_Deny:  "Leugnen",

_Heater:"Blase Entnebeln",

_Heater_setting:"Blase Entnebeln Einstellung",

_Heater_note:"Wichtiger Hinweis: Um die Gefahr von Verbrühungen zu vermeiden, schalten Sie bitte die Blase Entnebeln Funktion ein, wenn Sie die Kamera installieren",

_Setting:"Einstellung",

_Menu_SD_playback:"SD Playback",

_Msnapshot_note:"This page lists only record files stored on local SD card.",

_Msnapshot_remain:"Percent storage remaining:",

_Delete_all:"Delete All",

_Loading_data:"Loading data...",

_Loading_note:"Please wait as the data for your selection is loaded.",

_Reloading_note:"Please wait as the settings are reloaded.",

_Reloading_data:"Reloading data...",

_Deleting:"Deleting",

_SD_delete_all_confirm:"This will delete all mp4 files on the card and may take a long time. The SD card may not be removed during this time.Continue?",

_SD_delete_file:"Delete this file?",

_Higher_Frame_Rate: "Higher Frame Rate",

_Schedule_Reboot: "Schedule Reboot",

_Reboot_time: "Start Time",

_Fisheye: "Fisheye",

_Panaroma: "Panaroma",

_Quad: "Quad",

_Fish_view1: "View1",

_Fish_view2: "View2",

_Fish_view3: "View3",

_Fish_view4: "View4",

_msi_warning_confirm:  "The activex controller is not detected, do you want to download and install?",

_Position: "Position",

_Up_left: "Up-left",

_Up_middle: "Up-middle",

_Up_right:"Up-right",

_Bottom_left:"Bottom-left",

_Bottom_middle:"Bottom-middle",

_Bottom_right:"Bottom-right",

_External: "External",

_:  ""

}

