var lang_french={ 
_Live:  "Vue en direct",

_Live_fish: "Fisheye View",

_Administrator:  "Administrateur ",

_User:  "Utilisateur",

_Logout:  "Déconnexion",

_Language:  "Langue",

_Snapshot:  "capture",

_Manual_Recording:  "Enregistrement manuel",

_Media_Player:  "Média joueur",

_Lang_en:  "English",

_Lang_zh_cn:  "简体中文",

_Lang_zh_tw:  "繁體中文",

_Lang_french:  "Français",

_Lang_german:  "Deutsche",

_Lang_italian:  "Italiano",

_Lang_portuguese:  "Português",

_Lang_spanish:  "Español",

_Lang_russian:  "Pусский",

_Lang_japanese:  "日本語",

_PlayStream1:  "Lecture flux1 ",

_PlayStream2:  "Lecture  flux2 ",

_PlayStream3:  "Lecture flux3 ",

_Configuration:  "Configuration",

_Menu_Image:  "Paramètres d'image",
_Codec:  "Codec",
_Current_Compression_Mode:  "Mode compression actuel",
_Current_Profile:  "Profil actuel",
_Profile:  "Profil",
_Edit_Profile:  "Modifier profil",
_Compression_Profiles:  "Profils de compression",
_CBR:  "CBR",
_VBR:  "VBR",
_Resolution:  "Résolution",
_Frame_Rate:  "Taux d'images",
_GOP_Length:  "Longueur GOP",
_Rate_Control:  "Contrôle de taux",
_VBR_BitRate_Max:  "Taux de bits VBR max",
_VBR_BitRate_Min:  "Taux de bits VBR min",
_CBR_BitRate:  "Taux de bits CBR",
_Quality:  "Qualité",
_SaveProfile:  "Enregistrer profil",
_High:  "Élevé",
_Mid:  "Moy",
_Low:  "Faible",
_Qos:  "QoS (DSCP) Codepoint ",
_Menu_Image_exposure:  "Exposition",
_Exposure_Mode:  "Mode exposition",
_Auto_Exposure:  "Exposition auto",
_AES:  "AES",
_ALC:  "ALC",
_Flickerless:  "Anti-scintillement",
_Slow_Shutter:  "Obturation lente",
_Max_Gain:  "Gain maximal",
_Manual_Exposure:  "Exposition manuelle ",
_Shutter_Speed:  "Vitesse d'obturation",

_Manual_Gain:  "Gain manuel",

_Illumination_Control:  "Contrôle de l'illumination",

_Exposure_MISC:  "Exposition avancée",

_EV_adjustment:  "Compensation EV",

_Day_Night:  "Jour et Nuit",

_Day_to_Night:  "Seuil jour vers nuit",

_Night_to_Day:  "Seuil nuit vers jour",

_Minus: "-",

_Plus: "+",

_Switch_Delay_Time:  "Commutateur de délai",

_Adc_block:  "Détection des valeurs actuelles",

_Noise_Reduction:  "Réduction du bruit",

_BLC:  "BLC",

_WDR:  "WDR",

_upper_2_3rd:  "2/3 supérieurs",
_lower_2_3rd:  "2/3 inférieurs",
_center_1_3rd:  "1/3 central",
_center_1_6th:  "1/6 central",
_Left:  "Gauche",
_Right:  "Droite",
_Full:  "Complet",

_Custom: "Personnaliser",

_ir_mode:  "Mode IR ",
_ir_level:  "Niveau IR ",
_Menu_Image_white_balance:  "Balance du blanc",
_White_Balance_Mode:  "Mode balance du blanc",
_R_Gain:  "Gain R",
_G_Gain:  "Gain V",
_B_Gain:  "Gain B",
_Menu_Image_basic_color:  "Couleur de base",
_Brightness:  "Luminosité ",
_Contrast:  "Contraste ",
_Hue:  "Teinte ",
_Saturation:  "Saturation",
_Sharpness:  "Netteté",
_Gamma_Correction:  "Correction gamma",
_Flip_Mirror:  "Orientation vidéo",
_Flip:  "Retourner",
_Mirror:  "Miroir",
_Both:  "Les deux",

_Menu_Image_smart_encoding: "Codage intelligent",

_Menu_Image_privacy:  "Zone de confidentialité",

_Menu_Image_roi:  "ROI",

_Privacy_Color_Setting:  "Paramètres couleur confidentialité",
_Black:  "Noir",
_Grey:  "Gris",
_White:  "Blanc",
_Save_Mask_Zone:  "Enregistrer zone masque",
_Clean_Mask_Zone:  "Effacer zone masque",
_Save_Window:  "Enregistrer la fenêtre",

_Clean_Window:  "Nettoyer la fenêtre",

_Menu_Image_focus:  "Contrôle objectif distant",

_Focal_Length_Control:  "Contrôle zoom",

_Focal_window: "Zone de mise au point",

_Day_Night_Focus_Control:  "Contrôle de la mise au point diurne & nocturne",

_Speed:  "Vitesse zoom",
_Zoom_In:  "Zoomer",
_Zoom_Out:  "Dézoomer",
_Out_Slow:  "<",
_Out_High:  "<<",
_In_Slow:  ">",
_In_High:  ">>",
_Zoom:  "Zoom ",
_Focus:  "Mise au point",
_Focus_Control:  "Contrôle mise au point ",
_Focus_Manual_Continue:  "Mise au point manuelle continue",
_Focus_Near:  "Mise au point proche",
_Focus_Far:  "Mise au point distante",
_Focus_Manual_Jog:  "Pas de mise au point manuelle",
_Focus_Coarse:  "Pas normal",
_Focus_Fine:  "Pas fin",
_One_Push:  "AF à une pression",
_Do_Focus:  "Commencer mise au point",
_Calibration_Control:  "Etalonnage ",
_Do_Calibration:  "Commencer étalonnage",
_Menu_Network:  "Paramètres réseau",
_Menu_Network_ip:  "Réseau",
_Camera_Name:  "Nom caméra",
_DHCP:  "DHCP",
_IP_Address:  "Adresse IP ",
_Subnet_Mask:  "Masque de sous-réseau",
_Default_Gateway:  "Passerelle par défaut",
_Primary_DNS:  "DNS primaire",
_Secondary_DNS:  "DNS secondaire",
_UPNP:  "UPnP",
_Action:  "Action",
_OSD:  "OSD ",
_Network_setting:  "Paramètres réseau",
_View_current_network_setting:  "Afficher les paramètres réseau actuels",
_IPv4_addr_conf:  "Configurer adresse IPv4",
_Http_port:  "Port HTTP",
_Https_port:  "Port HTTPS",
_IPv4_addr:  "Adresse IPv4",

_IPv6: "IPv6",

_IPv6_addr_conf:  "Configurer adresse IPv6",

_Accept_IPv6_router:  "Accepter les publicités du routeur IPv6 ",

_Enable_dhcpv6:  "Activer DHCPv6",

_IPv6_default_router_addr:  "IPv6 adresse du routeur par défaut ",

_IPv6_addr:  "Adresse IPv6",

_IPv6_dns:  "DNS IPv6 ",

_subnet_prefix_length:  "Sous-réseau de longueur de préfixe ",
_bonjour:  "Bonjour ",
_text:  "Texte",
_hostname:  "Nom d'hôte ",
_View:  "Voir",
_Current_network_setting:  "Paramètres réseau actuels ",
_FTP:  "FTP",
_Max_Simultaneous_Connection:  "Nombre max de connexions simultanées",
_FTP_Function:  "Fonction FTP ",
_RTSP:  "RTSP",
_Authentication:  "Authentification ",
_RTSP_Stream:  "Flux RTSP",
_Transfer_Type:  "Type de transfert ",
_URL:  "URL",
_Multicast_Address:  "Adresse multicast",
_Metadata:  "Métadonnées ",
_Unicast:  "Unicast",
_Multicast:  "Multicast",
_Menu_Network_snmp:  "SNMP",
_SNMP_V:  "SNMP v",
_User_Name:  "Nom d'utilisateur",
_Read_Write_Community_String:  "Lire / écrire chaîne communauté ",
_Read_Community_String:  "Lire chaîne communauté",
_Write_Community_String:  "Écrire chaîne communauté",
_SNMP_Trap:  "Trappe ",
_SNMP_Trap_Host:  "Hôte trappe",
_SNMP_Heartbeat:  "Rythme cardiaque ",
_SNMP_Heartbeat_Host:  "Hôte rythme cardiaque",
_SNMP_Heartbeat_Interval:  "Intervalle rythme cardiaque",
_Download_MIB:  "Télécharger MIB ",
_Download_Button:  "Télécharger ",
_Menu_8021x:  "802.1X",
_Protocol:  "Protocole",
_Inner_Auth:  "Auth interne",
_Username:  "Nom d'utilisateur",
_Anonymous_ID:  "ID anonyme",
_CA_Certificate:  "Certificat CA",
_Client_Certificate:  "Certificat Client",

_Private_Key:  "Clé privée",
_PEM_encoded_file:  "Fichier encodé par PEM",
_Delete:  "Supprimer",
_Private_Key_Password:  "Mot de passe de clé privée",
_No_Installed_Ca:  "Non installé (le certificat serveur non sûr ne sera pas vérifié)",
_No_Installed:  "Non installé",
_Installed:  "Installé (OK)",
_IP_Filter:  "Filtre IP",
_Mode:  "Mode",
_Protocol:  "Protocole",
_Menu_System:  "Paramètres système",
_Menu_System_date_time:  "Date et heure",
_Current_Server_Time:  "Heure serveur actuelle ",
_Synchronization_Mode:  "Mode synchronisation ",
_Set_Manual:  "Manuel",
_Date:  "Date",
_Time:  "Heure",
_Synchronize_with_Computer_Clock:  "Synchroniser avec PC",
_Synchronize_with_NTP_Server:  "Synchroniser avec serveur NTP",
_NTP:  "NTP ",
_NTP_Server:  "Serveur NTP",
_NTP_Synchronize_Period:  "Période synchronisation",
_NTP_Time_Adjustment_Test:  "Test NTP",
_Save_and_Test:  "Sauvegarder et tester",
_DST:  "DST",
_Time_Zone:  "Fuseau horaire",
_Daylight_Saving:  "Heure d'été",
_Menu_System_account:  "Gestion utilisateurs",
_User_List:  "Liste utilisateurs",
_New_List:  "Gestion compte",
_Access_Level:  "Niveau d'accès",
_New_User:  "Nouvel utilisateur",
_Delete_User:  "Supprimer utilisateur",
_Confirm_Delete_User:  "Voulez-vous vraiment supprimer cet utilisateur ?",
_Delete_User_note:  "La caméra n'autorise que six comptes. Pour en créer un nouveau, veuillez d'abord supprimer un compte existant.",
_User_field_note:  "Le nom d'utilisateur doit être composé de 4~40 caractères alphanumériques (a~z, 0~9, sensible à la casse).",
_Exist_account:  "Le compte existe déjà dans le système.",
_Passwd_field_note:  "Le mot de passe doit être composé de 4~40 caractères, ou le champ comprend le caractère illégal \'",
_Admin:  "Admin ",
_Password_Confirm:  "Mot de passe (Reconfirmez)",
_Guest:  "Invité",
_Menu_System_audio:  "Audio",
_Audio_In:  "Entrée audio",
_Level:  "Niveau",
_G711u:  "G.711 µ-law",
_G711a:  "G.711 a-law",
_Audio_Out:  "Sortie audio",
_alarm_in:  "Entrée alarme",
_Menu_sys_heater:  "Bubble désembuage",
_current_power_source:  "Alimentation actuelle Source",
_24v:  "AC24V",
_poe:  "PoE",
_heater_note:  "Avis important: Bubble désembuage Chauffage est uniquement pris en charge par une source d'alimentation 24 V ",
_heater_warning:  "AC24V doit être connecté avant d'allumer Bubble",
_Menu_System_firmware:  "Firmware",
_System_Information:  "Informations système ",
_Firmware_Version:  "Version du firmware",
_MAC_Address:  "Adresse MAC",
_MCU_Version:  "Version MCU",
_Model_Name:  "Nom de modèle",
_Firmware_Update_and_Package_Install:  "Mise à niveau firmware et installation package ",
_Upload:  "Transférer",
_Video_Type:  "Type vidéo ",
_Camera_Type:  "Type système",
_NTSC:  "NTSC",
_PAL:  "PAL",
_Import_Configuration_Settings:  "Importer configurations utilisateur",
_Export_Configuration_Settings:  "Exporter configurations utilisateur",
_Restart_Camera:  "Redémarrer caméra",
_Software_Factory_Default:  "Paramètres d'usine du logiciel",
_Hardware_Factory_Default:  "Paramètres d'usine du matériel distant",
_Import_File:  "Importer",
_Export_File:  "Exporter",
_Menu_System_systemlog:  "Journal système",
_Download_Log:  "Journal de téléchargement",
_Refresh:  "Actualiser",
_Clean:  "Nettoyer",
_Menu_Event:  "Paramètres d'événements",
_Menu_Event_motion_detection:  "Détection de mouvement",
_Sensitivity:  "Sensibilité",
_Alarm:  "Alarme",
_Alarm_Input:  "Entrée alarme",
_NO:  "NO",
_NC:  "NC",
_Alarm_Output:  "Sortie alarme",
_Alarm_output_duration:  "Durée",
_Infinite:  "Infini",
_audio_detection:  "Détection audio",
_audio_alaram_level:  "Niveau Alarme Audio ",
_audio_activity:  "Activité audio",
_Menu_Record:  "Paramètres enregistrement",
_Menu_Record_ftp:  "Enregistrement FTP",
_FTP_Record_Conditions:  "Conditions enregistrement FTP",
_Scheduled:  "Calendrier",
_Alarm_In:  "Entrée alarme",
_FTP_Server:  "Serveur FTP ",
_Scheduled_Recording_Table:  "Enregistrement calendrier sur FTP ",

_Scheduled_Recording_SD_Table:  "Enregistrement calendrier sur SD ",

_Day:  "Jour",

_Monday:  "Lundi",
_Tuesday:  "Mardi",
_Wednesday:  "Mercredi",
_Thursday:  "Jeudi",
_Friday:  "Vendredi",
_Saturday:  "Samedi",
_Sunday:  "Dimanche",
_Schedule:  "Calendrier",
_Recording_Cycle:  "Cycle d'enregistrement",
_Recording_Time:    "Temps d'enregistrement",
_Record_File_Name:  "Préfixe du nom du fichier",
_Server_Path:  "Chemin serveur",
_Second:  "(Deuxième)",
_All_Day:  "Tous les jours",
_Alarm_Setting:  "Enregistrement événement alarme sur FTP (capture)",
_Pre_Recording_Frame:  "Trame Pré enregistrement",
_Pre_Recording_Cycle:  "Pré cycle d'enregistrement",
_Recording_Frame:  "Enregistrement image",
_File_Name:  "Nom du fichier",
_Motion_Setting:  "Enregistrement événement mouvement sur FTP (capture)",
_AM:  "Matin",
_PM:  "Apres Midi",
_Menu_Record_smtp:  "Enregistrement SMTP",
_SMTP_Record_Conditions:  "Conditions enregistrement SMTP",
_Recording_Mode:  "Mode enregistrement",
_SMTP_Server:  "Serveur SMTP ",
_Sender_Mail_Address:  "Adresse e-mail expéditeur",
_No_Auth:  "No_Auth",
_SMTP_Plain:  "SMTP_Plain",
_Login:  "Connexion",
_TLS_TTLS:  "TLS_TTLS",
_Condition_Settings_Alarm:  "Message e-mail (événement alarme)",
_Subject:  "Sujet",
_Message:  "Message",
_Attach_Image:  "Joindre image",
_Condition_Settings_Motion:  "Message e-mail (événement mouvement)",
_Email_Address_List:  "Liste d'adresses e-mail ",
_SMTP_No:  "No.",
_Address:  "Adresse",
_Menu_Record_sd:  "Enregistrement SD",
_SD_Record_Conditions:  " Conditions enregistrement SD",
_Network_Loss:  "Perte réseau",
_Alarm_Recording_Time:  "Heure d'enregistrement d'alarme",
_Motion_Recording_Time:  "Heure d'enregistrement de mouvements",
_OverWrite:  "Écrasement auto",
_SD_Card_Information:  "Informations carte SD",
_Usage:  "Utilisation",
_SD_Format:  "Format SD",
_Format:  "Format",
_record_schedule:  "Horaire planification",
_edit_month_schedule:  "Editer Mois planification",
_edit_week_schedule:  "Editer Semaine planification",
_edit_day_schedule:  "Editer la planification Jour",
_month_group:  "Mois du groupe",
_week_group:  "Semaine du groupe",
_day_group:  "Jour de groupe",
_week:  "Semaine",
_hour:  "Heure",
_minute:  "Minute",
_start_time:  "Heure de début",
_end_time:  "Heure de fin",
_to:  "à",
_close:  "Proche",
_status:  "Statut",
_save_event:  "Sauvegarder l'événement",
_forever:  "Toujours",
_month:  "Mois",
_record_type:  "Type d'enregistrement",
_sd_record_setting:  "Paramètres d'enregistrement SD",
_SD_Card_File_Brpwser:  "Navigateur de fichiers de la carte SD",
_View_Files:  "Afficher les fichiers",
_Showing:  "Affichage",
_Page:  "page",
_Save:  "Enregistrer",
_Reset_to_Default:  "Réinitialiser aux valeurs par défaut",
_Medium:  "Moyen",
_Type:  "Type",
_ON:  "ON",
_OFF:  "OFF",
_Color:  "Couleur",
_BW:  "N/B",
_Auto:  "Auto",
_Manual:  "Manuel",
_Enable:  "Activer",
_Start:  "Début",
_Stop:  "Arrêter",
_Password:  "Mot de passe",
_Login_ID:  "ID connexion",
_Port:  "Port",
_Motion:  "Mouvement",
_BasicSetting:  "Paramètres de base",
_Not_yet:  "Pas encore",
_Msg_PleaseConfirmPassword:  "Confirmez votre mot de passe.",
_Msg_PleaseSpecifyFW:  "Veuillez spécifier le chemin du firmware !",
_Msg_PleaseSpecifyIm:  "Veuillez spécifier le chemin du fichier d'importation !",
_Msg_PleaseSpecifyImName:  "Impossible d'ouvrir le fichier. Vérifiez que le format de fichier est *.XML.",
_Format_MJPEG_Warning:  "Aucun codec MJPEG !\nVeuillez choisir un mode de codec convenable dans Configuration->Paramètres d'image->Page codec.",
_Format_H264_Warning:  "Aucun codec H.264 !\nVeuillez choisir un mode de codec convenable dans Configuration->Paramètres d'image->Page codec.",
_SD_Card_Warning:  "Pas d'espace pour stocker les données !",
_SD_Card_format:  "Ceci formatera la carte SD ! Voulez-vous vraiment continuer ?",
_Firmware_upgrade_Warning:  "Voulez-vous vraiment mettre le firmware à niveau ?",
_Reboot_Warning:  "Ceci redémarrera la caméra ! Voulez-vous vraiment continuer ?",
_SW_Reboot_Warning:  "Tous les paramètres en dehors de ceux de la section réseau seront rétablis aux valeurs d'usine, et la caméra redémarrera automatiquement. Continuer ?",
_HW_Reboot_Warning:  "Tous les paramètres dont ceux de la section réseau seront rétablis aux valeurs d'usine, et la caméra redémarrera automatiquement. Continuer ?",
_Waiting_Warning:  "Redémarrage de la caméra, veuillez patienter... ",
_Import_Warning:  "Voulez-vous vraiment importer ce fichier ?",
_Upload_Warning:  "Transfert du fichier en cours, veuillez patienter... ",
_Impport_Success_Warning:  "Succès de l'importation ! Redémarrage de la caméra, veuillez patienter... ",
_Impport_Fail_Warning:  "Échec de l'importation ! Redémarrage de la caméra, veuillez patienter... ",
_Ipfinder_Warning:  "Veuillez rechercher la nouvelle adresse IP de la caméra en vérifiant son adresse MAC sur IP Finder.",
_Camera_Type_Change_Warning:  "Changement de type de caméra, veuillez patienter... ",
_Firmware_Verify_Warning:  "Vérification du firmware, veuillez patienter... ",
_Firmware_Install_Warning:  "Installation du firmware, veuillez patienter... ",
_Firmware_Success_Warning:  "Mise à niveau du firmware réussie ! Redémarrage de la caméra, veuillez patienter... ",
_Firmware_Fail_Warning:  "Échec de mise à niveau du firmware ! Redémarrage de la caméra, veuillez patienter... ",
_Reset_to_default_Warning:  "Les paramètres de cette page seront réinitialisés aux valeurs par défaut ! Continuer ?",
_Initial:  "Initial",
_Both_emtpy:  "La résolution et le codec ne peuvent pas être désactivés.",
_Resoluion_emtpy:  "La résolution ne peut pas être désactivée.",
_Codec_emtpy:  "Le codec ne peut pas être désactivé.",
_Reloading:  "Rechargement des paramètres...",
_Datetime_manual_note:  "La date et l'heure sont au mauvais format. Exemple : aaaa/jj/mm hh:mm:ss",
_Network_Camera:  "Caméra réseau",
_Information:  "Informations",
_Account_Management:  "Gestion compte",
_Event_log:  "Journal d'événements",
_Account_setting:  "Paramètres compte",
_Initialize:  "Initialiser",
_Alarm_in_out:  "E/S alarme",
_Email_Notification:  "Notification e-mail",
_Fixed:  "Ajuster",
_Real:  "1:1",
_Full_Screen:  "Plein écran",
_no_card:  "Aucune carte !",
_port_field_warning:  "Le numéro de port de domaine doit être utilisé pour un autre système,veuillez ré-entrer à nouveau.",
_msi_warning:  "Veuillez fermer cette fenêtre de navigateur lorsque  le téléchargement du contrôleur ActiveX est complet  et installé.",
_quicktime_install_note:  "Quicktime 7.5.5 ou supérieur est requis pour ce flux.",
_quicktime_download_note:  "Veuillezconsulter votre disque ressources ou aller à",
_invalid_ipv6_addr:  "L'adresse IPv6 n'est pas valide.",
_invalid_ipv6_prefix_length:  "La longueur du préfixe de sous-réseau n'est pas valide.",
_video:  "Vidéo",
_none:  "AUCUNE",
_privacy:  "Confidentialité",
_v3_auth_note:  "La clé d'authentification doit faire entre 8 et 64 caractères.",
_v3_privacy_note:  "La clé privée doit faire entre 8 et 64 caractères.",
_player:  "joueur",
_interval_note:  "La valeur doit être supérieure à 30.",
_Alarm_Message:  "Mot doit être compris entre 2 et 200 caractères",

_NAT_Setting:  "Cadre Net",

_Rtsp_Port:  "RTSP Port sur ​​NAT",

_Menu:  "Menu",

_Stream:  "Flux",

_Smart_Encoding_Region: "Région de codage intelligent",

_Allow:  "Permettre",

_Deny:  "Nier",

_Heater:"Désembuage",

_Heater_setting:"Paramètres de désembuage",

_Heater_note:"Notice importante : pour éviter les risques de brûlure, veuillez éteindre la fonction de désembuage lorsque vous installez la caméra",

_Setting:"Réglages",

_Menu_SD_playback:"SD Playback",

_Msnapshot_note:"This page lists only record files stored on local SD card.",

_Msnapshot_remain:"Percent storage remaining:",

_Delete_all:"Delete All",

_Loading_data:"Loading data...",

_Loading_note:"Please wait as the data for your selection is loaded.",

_Reloading_note:"Please wait as the settings are reloaded.",

_Reloading_data:"Reloading data...",

_Deleting:"Deleting",

_SD_delete_all_confirm:"This will delete all mp4 files on the card and may take a long time. The SD card may not be removed during this time.Continue?",

_SD_delete_file:"Delete this file?",

_Higher_Frame_Rate: "Higher Frame Rate",

_Schedule_Reboot: "Schedule Reboot",

_Reboot_time: "Start Time",

_Fisheye: "Fisheye",

_Panaroma: "Panaroma",

_Quad: "Quad",

_Fish_view1: "View1",

_Fish_view2: "View2",

_Fish_view3: "View3",

_Fish_view4: "View4",

_msi_warning_confirm:  "The activex controller is not detected, do you want to download and install?",

_Position: "Position",

_Up_left: "Up-left",

_Up_middle: "Up-middle",

_Up_right:"Up-right",

_Bottom_left:"Bottom-left",

_Bottom_middle:"Bottom-middle",

_Bottom_right:"Bottom-right",

_External: "External",

_:  ""

}

