var LT_JAPAN={
_User: "ユーザー",
_Logout: "ログアウト",
_Live: "ライブ ビューアー",
_Configuration: "設定",
_Video: "映像",
_Network: "ネットワーク",
_Privacy_zone: "プライバシーゾーン",
_Exposure: "露出",
_Whtiebalance: "ホワイトバランス",
_Basic_color: "基本カラー",
_Quality: "画質設定",
_Ftp_Server: "FTP Server",
_Ftp: "FTP",
_Rtsp: "RTSP",
_Snmp: "SNMP",
_8021x: "802.1X",
_Roi: "ROI",
_Ddns: "DDNS",
_Ldap: "LDAP",
_Ssl: "SSL",
_Date_time: "日時",
_Audio: "音声",
_Firmware: "ファームウェア",
_Initialize: "初期化",
_Account_mag: "アカウント管理",
_Osd: "OSD",
_User_name: "ユーザー名",
_Password: "パスワード",
_Login: "Login",
_Basic_setting: "基本設定",
_Profile: "プロファイル",
_Current_profile: "現在のプロファイル",
_Codec: "圧縮方式",
_Frame_rate: "フレームレート",
_Rate_control: "ビットレートモード",
_CBR_bit_rate: "ビットレート",
_BLC: "逆光補正(BLC)",
_Exposure_mode: "露出モード",
_Sensitivity: "感度",
_Shutter_speed: "シャッター速度",
_Mode: "モード",
_R_Gain: "Rゲイン",
_B_Gain: "Bゲイン",
_Brightness: "明るさ",
_Contrast: "コントラスト",
_Saturation: "彩度",
_Hue: "色相",
_Sharpness: "鋭さ",
_Gamma_correction: "ガンマ補正",
_Noise_reduction: "ノイズリダクション",
_IPv4_address: "IPv4アドレス",
_Http_port: "HTTPポート",
_UPnP: "UPnP",
_Https_port: "HTTPSポート",
_Enable: "有効",
_Authentication: "認証",
_Login_id: "ログイン名",
_Port: "ポート",
_SNMP_v: "SNMP v",
_Read_community_string: "読み取りコミュニティー名",
_Write_community_string: "書き込みコミュニティー名",
_URL: "URL",
_Stream: "ストリーム",
_SNMP_trap: "トラップ",
_SNMP_heartbeat: "ハートビート",
_Address: "通知先メールアドレス",
_heartbeat_interval: "ハートビート間隔",
_Anonymous_id: "匿名 ID",
_Protocol: "プロトコル",
_Upload: "アップロードする",
_CA_certificate: "CA証明書",
_Type: "入力方式",
_Download_mib: "MIBをダウンロード",
_Current_server_time: "現在の日時",
_Synchronization_mode: "同期モード",
_New_user: "新規ユーザー",
_Delete_user: "ユーザー削除",
_High: "High",
_Medium: "中",
_Mid: "中",
_Low: "低",
_On: "ON",
_Off: "OFF",
_Auto: "自動",
_Flickerless: "フリッカレス",
_Manual: "手動",
_Wdr: "ワイドダイナミックレンジ(WDR)",
_Full: "全画面",
_Upper_2_3rd: "上部の2/3",
_Lower_2_3rd: "下部の2/3",
_Central_1_3rd: "中央の1/3",
_Central_1_6th: "中央の1/6",
_Left: "左",
_Right: "右",
_Color: "カラー",
_Bw: "モノクロ",
_Fast: "速い",
_Normal: "標準",
_Slow: "遅い",
_Mirror: "ミラー",
_Flip: "フリップ",
_Both: "両者とも",
_G711a: "G.711 µ-law",
_G711u: "G.711 µ-law",
_None: "無し",
_Grey: "グレー",
_Text: "テキスト",
_Black: "黒",
_White: "白",
_Dhcp: "DHCP",
_Alarm: "アラーム",
_Motion: "動作検知",
_Schedule: "スケジュール",
_Synchronize_with_pc: "PCに同期",
_Synchronize_with_ntp: "NTPサーバーに同期",
_Date: "日付",
_NTP_test: "NTP実行テスト",
_Level: "レベル",
_Time: "時刻",
_Import_file: "インポート",
_Export_file: "エクスポート",
_Software_factory_default: "設定データ初期化",
_Firmware_version: "バージョンアップ",
_MAC_address: "MACアドレス",
_Account_setting: "アカウント設定",
_User_list: "ユーザーリスト",
_Access_level: "アクセスレベル",
_Admin: "Admin",
_Snapshot: "スナップショット",
_Privacy_color_setting: "プライバシーゾーン表示設定",
_Clean: "クリーン",
_Focus_control: "フォーカス制御",
_Subject: "メール件名",
_Message: "メール本文",
_Monday: "月曜日",
_Tuesday: "火曜日",
_Wednesday: "水曜日",
_Thursday: "木曜日",
_Friday: "金曜日",
_Saturday: "土曜日",
_Sunday: "日曜日",
_Attach_image: "画像添付",
_Email_address_list: "メール通知先",
_Num_no: "No.",
_Action: "有効",
_No_auth: "No_Auth",
_Smtp_plain: "SMTP_Plain",
_Tls_ttls: "TLS_TTLS",
_Infinite: "無限",
_Delete: "削除",
_Zoom_control: "ズーム制御",
_Zoom_in: "ズームイン",
_Zoom_out: "ズームアウト",
_Auto_focus: "Auto Focus",
_One_push_af: "オートフォーカス",
_Day_night_focus_ctrl: "Day & Night Focus Control",
_Start: "開始",
_Stop: "終了",
_View_current_network_settings: "最新のネットワーク設定表示",
_Manual_recording: "手動録画",
_Full_screen: "全画面",
_View: "表示",
_DSCP: "DSCP",
_GOP: "GOP",
_NO: "NO",
_NC: "NC",
_Primary_dns: "プライマリDNS",
_Secondary_dns: "セカンダリDNS",
_Download_log: "ログをダウンロード",
_System_log: "システムログ",
_No_Installed: "インストールされていない",
_SD_Format: "SDメモリカードフォーマット",
_Format: "フォーマット",
_Advanced_focus_ctrl:"Advanced Focus Control",
_Modify: "変更",
_Add: "追加",
_Cancel: "キャンセル",
_Restore_position: "位置の復元",
_Handler: "ハンドラー",
_Firewall: "ファイアウォール",
_General: "一般",
_Encode: "エンコード",
_Images: "画像",
_System: "システム",
_Account: "アカウント",
_Event: "イベント",
_Source: "ソース",
_Advance_configurartion: "詳細設定",
_MSI_dwonload_note: "プラグインのダウンロードおよびインストールが完了したら、ブラウザを起動し直してください。",
_Please_click_here: "%s をクリックしてファイルをダウンロードしてください",
_Here: "こちら",
_FM_uploading: "ファームウェアをアップロード中…",
_FM_uncompress: "ファームウェアを解凍中…",
_FM_checking: "ファームウェアを確認中…",
_FW_installing: "ファームウェアをインストール中…",
_FW_success: "ファームウェア更新が成功、カメラを再起動中…",
_FW_fail: "ファームウェア更新が失敗、カメラを再起動中…",
_Reboot_complete: "再起動が完了",
_Please_wait: "お待ちください",
_System_loading: "システムをロード中…",
_File_uploading: "ファイルをアップロード中…",
_Please_search_ip: "IPファインダでMACアドレスを確認して、新規カメラのIPアドレスを検出してください。",
_Upload_cert_file_fail: "認証ファイルアップロード失敗。",
_Change_these_setting_will_logout: "これらの設定を変更すると、ログアウトして再度ログインする必要があります",
_Do_you_want_change: "ユーザーおよびグループ管理設定を変更しますか??",
_Compression: "圧縮",
_Quality_level: "画質",
_Max_bit_rate: "最大ビットレート",
_DC_iris_control: "DCアイリス制御",
_P_iris_control: "Pアイリス制御",
_P_iris_level: "Pアイリスレベル",
_Fixed_iris_control: "固定アイリス制御",
_Day_night_setting: "昼夜設定",
_Day_night_mode: "昼夜モード",
_Day_to_night: "昼から夜へ",
_Night_to_day: "夜から昼へ",
_Switch_time: "切換え時間",
_ICR_mode: "ICRモード",
_IR_level: "IRレベル",
_IR_mode: "IRモード",
_IR_optimizer: "IRオプティマイザー",
_Digital_wdr: "デジタルWDR",
_EV: "EV",
_Gain: "ゲイン",
_HLC: "HLC",
_Max_shutter_time: "最大シャッター時間",
_Min_shutter_time: "最小シャッター時間",
_One_push: "1回押し",
_Mirror_flip_setting: "ミラー反転設定",
_Orientation: "方向",
_Defog: "デフォッグ",
_Device_name: "デバイス名",
_Enable_ldap: "LDAP を有効化",
_IP_settings: "IP設定",
_IPv4_subnet_mask: "IPv4 サブネットマスク",
_IPv4_default_gateway: "IPv4 デフォルトゲートウェイ",
_IPv6_enable: "IPv6 を有効化",
_IPv6_advert: "IPv6ルータキャスティングを許可",
_IPv6_dhcp: "DHCPv6を有効化",
_IPv6_default_router: "IPv6のデフォルトルータ・アドレス",
_IPv6_addr: "IPv6アドレス",
_IPv6_dns: "IPv6 DNS",
_Subnet_prefix_length: "サブネットプリフィックス長",
_IP_address: "IPアドレス",
_Enable_upnp: "UPnP を有効化",
_Friendly_name: "ニックネーム",
_Enable_ssl: "SSL有効化",
_SSL_certificate_msg: "SSL有効化の前にSSL認証をインストールまたは生成してください。",
_Metadata: "メタデータ",
_Auto_connect: "自動接続",
_Address_type: "アドレスタイプ",
_Multicast_url: "マルチキャストURL",
_Video_address: "ビデオアドレス",
_Video_port: "ビデオポート",
_Audio_address: "オーディオアドレス",
_Audio_port: "オーディオポート",
_Meta_address: "メタアドレス",
_Meta_port: "メタポート",
_Trap_community_string: "トラップコミュニティーストリング",
_Authentication_mode: "認証モード",
_Authentication_password: "認証パスワード",
_Privacy_mode: "プライバシーモード",
_Privacy_password: "プライバシーパスワード",
_Target_ip: "ターゲットIP",
_Download: "ダウンロード",
_Status: "状態",
_Inner_authentication: "内部認証",
_Server_address: "サーバーアドレス",
_Save_and_test: "保存およびテスト",
_Domain: "ドメイン",
_Filter: "フィルター",
_Generate_certificate: "認証の生成",
_Method: "メソッド",
_Certificate_area: "認証エリア",
_Country_code: "国コード",
_Organization_name: "組織名",
_Province_name: "地区名",
_Organization_unit_name: "組織部門名",
_City_name: "都市名",
_Email_address: "Eメールアドレス",
_Common_name: "通称",
_Certificate_information: "認証情報",
_Organization: "組織 ",
_Country: "国",
_Locality: "地方",
_Issuer: "発行者",
_Valid_from: "発効日付",
_To: "発効期限",
_Upload_certificate: "認証のアップロード",
_Country_code_note: "2文字の国コード、例：US",
_Organization_note: "例：会社名。",
_Province_note: "州または地方の正式名。",
_Department_note: "例：部門またはセクション。",
_Common_name_note: "この装置のホスト名またはIPアドレス。",
_Delete_certificate: "認証の削除",
_Server_settings: "サーバー設定",
_Server: "サーバ",
_Base_dn: "ベースDN",
_Bind_dn_template: "バインドDNテンプレート",
_Search_template: "テンプレートの検索",
_Group_mappings: "グループマッピング",
_Admins: "管理者",
_Operators: "オペレーター",
_Users: "ユーザー",
_Sync_with_manual: "マニュアルでの同期",
_NTP_setting: "NTP設定",
_NTP_from_dhcp: "DHCPサーバーからの割り当て",
_NTP_period: "同期の周期",
_Time_zone_setting: "タイムゾーン設定",
_Time_zone_area: "エリア",
_Audio_in_setting: "オーディオ入力設定",
_Encoding: "エンコーディング",
_Audio_out_setting: "オーディオ出力設定",
_Import_setting: "インポート設定",
_Export_setting: "設定のインポート",
_Configuration_setting: "構成の設定",
_Reboot: "再起動",
_Hardware_factory_default: "ハードウェアの工場デフォルト",
_System_information: "システム情報",
_Hardware_version: "ハードウェアバージョン",
_Product_name: "製品名",
_Serial_number: "シリアル番号",
_Firmware_upload: "ファームウェアのアップロード",
_Upgrade: "アップグレード",
_Background_color: "背景色",
_Text_color: "文字の色",
_Text_input: "文字入力",
_Location_x: "位置X",
_Location_y: "位置Y",
_High_profile: "ハイプロファイル",
_Main_profile: "メインプロファイル",
_Advanced: "詳細",
_Shutter_priority: "シャッター優先",
_Operator: "オペレーター",
_In: "入力",
_Out: "出力",
_Max: "最大",
_Pppoe: "PPPoE",
_Aac: "AAC",
_Transparent: "トランスペアレント",
_IP_and_device_name: "IPおよびデバイス名",
_User_input: "ユーザー入力",
_From_dhcp_server: "DHCPサーバーから",
_Self_signed: "自己サインイン",
_Request: "リクエスト",
_Allow: "許可",
_Deny: "不許可",
_Lens_control: "レンズ制御",
_Event_source: "イベントソース",
_Event_handler: "イベントハンドラー",
_Face: "フェイス",
_Defocus: "ピント外れ",
_Tamper: "改ざん",
_Alarm_out: "アラーム出力",
_Email: "Eメールアドレス",
_NAS: "NAS",
_Record_setting: "録画設定",
_Sound: "サウンド",
_Zone_setting: "ゾーン設定",
_SD_card: "SDカード",
_Multicast_address_setting: "マルチキャストアドレス接続",
_Edge_record: "エッジ記録",
_NAS_record: "NAS記録",
_Store_to_edge: "エッジに保存",
_Store_to_ftp: "FTPに保存",
_Store_to_nas: "NASに保存",
_Recording: "録画",
_Handlers: "ハンドラー",
_Wire: "ワイヤー",
_Wireless: "ワイヤレス",
_Arming_schedule_setting: "監視スケジュール設定",
_Audio_out: "オーディオ出力",
_Audio_sound: "オーディオサウンド",
_Object_size: "対象サイズ",
_Motion_zone_area_setting: "モーションゾーンエリア設定",
_Zone: "ゾーン",
_Save_area: "エリアの保存",
_Edit: "編集",
_Condition: "条件",
_Wire_Network_conflict: "有線ネットワークの競合",
_Wire_Network_lost: "有線ネットワークの消失",
_Wireless_Network_conflict: "ワイヤレスネットワークの競合",
_Wireless_Network_lost: "ワイヤレスネットワークの消失",
_Trigger_interval: "トリガー間隔",
_Post_duration: "ポスト継続時間",
_On_time: "オン時間",
_Off_time: "オフ時間",
_Count: "カウント",
_Sender_settings: "差出人設定",
_Sender_email_address: "送信者Eメールアドレス",
_Mount_method: "マウント方法",
_Store_path: "保存パス",
_NAS_mount_status: "NASマウント状態",
_Capacity: "容量",
_Free_space: "空き容量",
_Online_offline: "オンライン/オフライン",
_Clip_duration: "クリップ継続時間",
_Record_type: "録画タイプ",
_Record_status: "記録状態",
_Clip_size: "クリップサイズ",
_Overwrite: "上書き",
_Mount_status: "マウント状態",
_Pre_event_capture_count: "プリイベントキャプチャカウント",
_Event_capture_interval: "イベントキャプチャ間隔",
_Post_event_capture_count: "ポストイベントキャプチャカウント",
_File_status: "ファイル状態",
_Delete_file: "ファイルの削除",
_Select_file: "ファイルの選択",
_Browser: "ブラウザ",
_Baseline_profile: "ベースラインプロファイル",
_Pulse: "パルス",
_Active: "アクティブ",
_Passive: "パッシブ",
_Audio_and_video: "オーディオおよびビデオ",
_One_shot: "1回撮影",
_Continuous: "連続",
_Digital: "デジタル",
_Absolute: "絶対",
_Relative: "相対",
_Far: "長距離",
_Near: "短距離",
_Wide: "ワイド",
_Tele: "望遠",
_Day_night_switch: "昼夜切換え",
_Day_night_switch_ctrl: "昼夜切換え制御",
_Tamperature: "温度",
_Zoom_trigger: "ズームトリガー",
_Sound_intensity_threshold: "サウンド強度閾値",
_Motion_detection: "モーション検知",
_Face_detection: "フェイス検知",
_There_are_unsaved: "このページには保存されていない変更があります。",
_Are_you_sure_to_leave: "このページから移動してもよろしいですか?",
_Import_successful: "インポート成功",
_Import_fail: "インポート失敗",
_Network_Interface_Information: "ネットワークインタフェース情報",
_Camera_Type: "カメラのタイプ",
_Wire_setting: "ワイヤー設定",
_Nic_type: "速度および二重モード",
_1G_full: "1.0 Gbps全二重",
_10M_full: "10 Mbps全二重",
_10M_half: "10 Mbps半二重",
_100M_full: "100 Mbps全二重",
_100M_half: "100 Mbps半二重",
_Warning_message: "警告メッセージ",
_Lens_does_not: "レンズはキャリブレーションされていません！！お買い上げ店にご連絡ください。",
_IR_control: "IR制御",
_WB_does_not: "WBはキャリブレーションされていません！！ATWモードは使用せず、お買い上げ店にご連絡ください。",
_Hash: "ハッシュ",
_Hostname: "ホスト名",
_Save: "保存",
_Lens_control_occurred: "レンズ制御で予期しない動作が発生しました。カメラを再起動して問題を解決してください。",
_Event_search: "イベント検索",
_Sec: "秒",
_Frame: "フレーム",
_Please_check_the_information: "ネットワーク->LDAPページの情報が正しいこと、さらにLDAPサーバーが動作中であることを確認してください。",
_Please_note_that_you: "誤りがあると、カメラにログインできない可能性がある点にご注意ください。",
_Ptz_setting: "PTZ設定",
_PTZ_Basic: "基本",
_PTZ_Position: "位置",
_PTZ_Patrol: "パトロール",
_PTZ_Pattern: "パターン",
_Power_on_action: "電源オン時の動作",
_HOME: "ホーム",
_LAST_ACTION: "直前の動作",
_AUTO_SCAN: "オート    スキャン   ",
_FRAME_SCAN: "フレーム     スキャン",
_RANDOM_SCAN: "ランダム    スキャン   ",
_AUTO_PATROL_1: "自動パトロール1",
_AUTO_PATROL_2: "自動パトロール2",
_AUTO_PATROL_3: "自動パトロール3",
_AUTO_PATROL_4: "自動パトロール4",
_INDOOR: "屋内",
_OUTDOOR: "屋外",
_Pantilt_setting: "パン/ティルト設定",
_Tilt_Angle: "ティルト角",
_Auto_flip: "自動反転",
_Pt_max_speed: "最大速度",
_Scan_setting: "スキャン設定",
_Scan_angle: "角度",
_Scan_speed: "速度",
_Limit_enable: "リミット有効",
_Zoom_Setting: "ズーム設定",
_Zoom_Limit: "ズーム限界",
_D_1X: "10X",
_D_2X: "20X",
_D_4X: "40X",
_D_8X: "80X",
_D_10X: "100X",
_Focus_Setting: "フォーカス設定",
_Focus_Mode: "フォーカスモード",
_Focus_Sensitivity: "フォーカス感度",
_Preset_Position: "プリセット位置",
_Preset_Set: "設定",
_Preset_Clear: "クリア",
_Patrol_Setting: "パトロール設定",
_Stop_Duration: "停止継続時間（秒）",
_Preset_Select: "プリセット選択",
_Patrol_1: "パトロール1",
_Patrol_2: "パトロール2",
_Patrol_3: "パトロール3",
_Patrol_4: "パトロール4",
_Patterm_Setting: "パターン設定",
_Pattern_1: "パターン1",
_Pattern_2: "パターン2",
_Pattern_3: "パターン3",
_Pattern_4: "パターン4",
_Pattern_Play: "再生",
_Ok: "OK",
_Data_loading: "データロード中",
_Initial_DB_success: "初期DB成功。",
_Event_type: "イベントタイプ",
_Start_time: "開始時間",
_End_time: "終了時間",
_Event_List: "イベントリスト",
_Network_Less: "ネットワーク無し",
_Search: "検索",
_Anaylsis: "分析",
_Refresh: "最新情報に更新",
_All_the_time: "常時",
_Lang_en:"English",
_Lang_zh_cn:"简体中文",
_Lang_zh_tw:"繁体中文",
_Lang_arabic:"العربية",
_Lang_czech:"Čeština",
_Lang_french:"Français",
_Lang_german:"Deutsch",
_Lang_hugrian:"Magyar",
_Lang_italian:"Italiano",
_Lang_japanese:"日本語",
_Lang_polish:"Polski",
_Lang_portuguese:"Português",
_Lang_russian:"Русский",
_Lang_spaish:"Español",
_Query_sd_card_live_time: "SDカード有効時間問い合わせ",
_This_will_reboot: "カメラが再起動されます。よろしいですか?",
_Camera_rebooting: "カメラ再起動中",
_Apply: "適用",
_Upper: "上方",
_Lower: "下方",
_Back_focus: "背部フォーカス",
_Language: "言語",
_Mic_in: "マイク入力",
_Line_in: "ライン入力",
_Alarm_id: "アラームID",
_Device_id: "デバイスID",
_Register_interval: "登録間隔",
_GB28181: "GB28181",
_Adjustable: "調節可能",
_Broad: "広帯域",
_Narrow: "狭帯域",
_Youtube_Live: "RTMP",
_Input_source: "入力ソース",
_Rtmp_url: "RTMP URL",
_SD_card_formatting: "SDカードフォーマット中",
_Corridor: "廊下",
_Corridor_will_not_mjpeg: "廊下モードはコーデックがMJPEGの場合は表示されません",
_Corridor_will_not_5m: "廊下モードは解像度が500万画素を超える場合は表示されません",
_Ldap_auth_failed: "ユーザーによるリモートサーバーへの認証が失敗しました。基本BN、バインドDNテンプレート、または検索テンプレートが正しくない可能性があります。",
_Http_live_streaming: "HTTPライブストリーミング",
_Hls_url: "HLS URL",
_Clean_up: "クリーンアップ",
_Dynamic_gop: "ダイナミックGOP",
_H264_advanced: "H264詳細",
_Lightstream: "ライトストリーム",
_Lightweight_stream:"ライトストリーム",
_Close: "閉じる",
_Full_open: "フルオープン",
_Bonjour: "Bonjour",
_Object_counting:"Object Counting",
_Loitering:"Loitering",
_Max_object_size:"Max Object Size",
_Min_object_size:"Min Object Size",
_Size_setting:"Size Setting",
_Line_setting:"Line Setting",
_Medium_high:"Medium High",
_Medium_low:"Medium Low",
_Line:"Line",
_Direction:"Direction",
_Video_analytics:"Video Analytics",
_Media_control:"メディア プレーヤー",
_Live_timing_relay:"Live View Latancy",
_Edge:"Edge",
_Intrusion:"Intrusion",
_Line_crossing:"Line Crossing",
_Lens_type:"Lens Type",
_Live_view_jitter:"Live View Jitter Buffer Length",
_Baudrate:"Baud Rate",
_Device_address:"Device Address",
_Preset:"Preset",
_Up:"Up",
_Right_up:"Right-Up",
_Right_down:"Right-Down",
_Down:"Down",
_Left_down:"Left-Down",
_Left_up:"Left-Up",
_Line_counting:"Line Counting",
_Borderline:"Border Line",
_iZone:"iZone",
_iStream:"iStream",
_EcoZone:"EcoZone",
_EcoFrame:"EcoFrame",
_Enhanced_h264:"Enhanced H.264",
_mSD_healthness:"mSD healthness",
_Area_counting:"Area Counting",
_Departure:"Departure",
_Event_setting:"イベント設定",
_Dewarp:"Dewarp",
_SFTP:"SFTP Server",
_Withdrawn:"Withdrawn",
_SD_playback: "SD再生",
_SD_stream_setting: "SDストリーム設定",
_Recording_stream: "録画ストリーム",
_Playback_setting: "再生設定",
_Playback: "再生",
_Playback_warning:"Record stream must be H264, Please choose a suitable codec mode on configuration mode on setup",
_Please_enter_time:"Please enter time",
_Playback_should_earlier_than_10_minutes:"Playback time should earlier than 10 minutes before current camera time.",
_Window_close_confirm:"Are you sure to close window?",
_: ""  
}
